(function (global) {
    var ns = global.ThemeMgrModules = global.ThemeMgrModules || {};
    var STYLE_ID = 'tm-avatar-page-style';
    function esc(value) { return String(value == null ? '' : value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
    function buildPageHtml() {
        return '<div class="tm-avatar-page" data-tm-avatar-page>' +
            '<input type="file" data-avatar-file accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" multiple hidden>' +
            '<div class="tm-search-bar" data-avatar-search-bar><div class="tm-search-wrap"><i class="fa-solid fa-magnifying-glass"></i><input class="tm-search-inp" data-avatar-search placeholder="搜索分类、标签、系列…" autocomplete="off"></div><button class="tm-search-clear" data-avatar-search-clear aria-label="清除搜索"><i class="fa-solid fa-xmark"></i></button></div>' +
            '<div class="tm-sortbar" data-avatar-sortbar><span style="font-size:.72em;opacity:.4;flex-shrink:0">排序：</span><button class="tm-sort-chip" data-avatar-sort="import-asc">导入正序</button><button class="tm-sort-chip on" data-avatar-sort="import-desc">导入倒序</button></div>' +
            '<div class="tm-catbar tm-avatar-catbar" data-avatar-catbar></div><div class="tm-batch-area" data-avatar-batch-area></div>' +
            '<div class="tm-avatar-page-notice" data-avatar-notice role="status" aria-live="polite" hidden></div>' +
            '<div class="tm-avatar-page-grid" data-avatar-grid><div class="tm-avatar-page-loading">正在读取头像库…</div></div></div>';
    }
    function styleText() { return [
        '.tm-app-page-avatars{display:block;place-items:initial;min-width:0;overflow:hidden;padding:0}',
        '.tm-avatar-page{height:100%;min-width:0;box-sizing:border-box;display:flex;flex-direction:column;overflow:hidden}',
        '.tm-avatar-page-notice{flex:0 0 auto;margin:9px 14px 0;padding:8px 10px;border:var(--tm-control-border-style,1px solid var(--tm-control-border,rgba(127,127,127,.16)));border-radius:var(--tm-control-radius,8px);background:var(--tm-control-bg,rgba(127,127,127,.06));color:inherit;font-size:.8em}.tm-avatar-page-notice[data-kind="loading"] i{display:inline-block;margin-right:6px;animation:tm-spin 1s linear infinite}.tm-avatar-page-notice[data-kind="error"]{border-color:currentColor}',
        '.tm-avatar-page-grid{min-width:0;min-height:0;flex:1 1 auto;overflow:auto;display:grid;grid-template-columns:repeat(auto-fill,minmax(112px,1fr));grid-auto-flow:row dense;grid-auto-rows:max-content;align-content:start;align-items:start;gap:9px;padding:12px}',
        '.tm-avatar-page-card,.tm-avatar-native-slot{min-width:0;width:100%;height:auto;aspect-ratio:1;align-self:start;position:relative;overflow:hidden;border:var(--tm-card-border-style,2px solid var(--tm-card-border,transparent));border-radius:var(--tm-card-radius,10px);background:var(--tm-card-bg,rgba(127,127,127,.06));box-shadow:var(--tm-card-shadow,none)}.tm-avatar-page-card{width:100%;aspect-ratio:1;align-self:start;cursor:pointer}.tm-avatar-page-card:focus-visible,.tm-avatar-native-slot:focus-visible{outline:2px solid var(--SmartThemeQuoteColor,#7c6daf);outline-offset:2px}',
        '.tm-avatar-page-thumb{position:absolute;inset:0;display:block;width:100%;height:100%;object-fit:cover;background:var(--tm-control-bg,rgba(127,127,127,.1))}',
        '.tm-avatar-native-slot{display:grid;place-items:center;cursor:pointer;color:inherit}.tm-avatar-native-slot>i{font-size:2.15em;opacity:.16}.tm-avatar-native-slot:hover>i{opacity:.27;color:var(--SmartThemeQuoteColor,#7c6daf)}',
        '.tm-avatar-card-active,.tm-avatar-card-check{position:absolute;right:7px;top:7px;z-index:2;width:23px;height:23px;place-items:center;border-radius:50%;background:rgba(0,0,0,.52);color:#fff;border:1px solid rgba(255,255,255,.55)}.tm-avatar-card-active{display:grid;font-size:.68em}.tm-avatar-card-check{display:none}.tm-avatar-page.is-batch .tm-avatar-card-active{display:none}.tm-avatar-page.is-batch .tm-avatar-card-check{display:grid}.tm-avatar-page-card.is-active{border-color:var(--SmartThemeQuoteColor,#7c6daf)}.tm-avatar-page-card.batch-sel{border-color:var(--SmartThemeQuoteColor,#7c6daf)}.tm-avatar-page-card.batch-sel .tm-avatar-card-check{background:var(--SmartThemeQuoteColor,#7c6daf)}',
        '.tm-avatar-page-loading,.tm-avatar-page-empty{grid-column:1/-1;align-self:center;justify-self:center;text-align:center}.tm-avatar-page-loading{padding:24px 16px;opacity:.55}.tm-avatar-page-empty{padding:18px 12px;font-size:.78em;opacity:.48}',
        '.tm-avatar-series-inline{grid-column:span var(--tm-avatar-series-size,2);min-width:0;display:grid;grid-template-columns:repeat(var(--tm-avatar-series-size,2),minmax(0,1fr));gap:9px}.tm-avatar-series-block{grid-column:1/-1;min-width:0;position:relative;overflow:hidden}.tm-avatar-series-track{display:grid;grid-auto-flow:column;grid-auto-columns:calc((100% - (var(--tm-avatar-series-cols,3) - 1)*9px)/var(--tm-avatar-series-cols,3));gap:9px;overflow-x:auto;overflow-y:hidden;scrollbar-width:none;-webkit-overflow-scrolling:touch;overscroll-behavior-x:contain}.tm-avatar-series-track::-webkit-scrollbar{display:none}.tm-avatar-series-block.is-expanded{overflow:visible}.tm-avatar-series-block.is-expanded .tm-avatar-series-track{grid-auto-flow:row;grid-auto-columns:initial;grid-template-columns:repeat(var(--tm-avatar-series-cols,3),minmax(0,1fr));overflow:visible}',
        '.tm-avatar-series-controls{position:absolute;right:6px;top:6px;z-index:4;display:flex;gap:4px;opacity:0;visibility:hidden;transform:translateY(-3px);transition:.18s;pointer-events:none}.tm-avatar-series-block.is-interacting .tm-avatar-series-controls,.tm-avatar-series-controls:focus-within{opacity:1;visibility:visible;transform:none;pointer-events:auto}.tm-avatar-series-control{width:32px;height:32px;display:grid;place-items:center;border:1px solid rgba(255,255,255,.28);border-radius:9px;background:rgba(0,0,0,.58);color:#fff;cursor:pointer}',
        '.tm-avatar-manage-summary{display:flex;align-items:center;gap:10px;margin-bottom:10px}.tm-avatar-manage-thumb{width:54px;height:54px;border-radius:10px;object-fit:cover;background:rgba(127,127,127,.1)}.tm-avatar-manage-summary>span{display:flex;min-width:0;flex-direction:column;gap:3px}.tm-avatar-manage-summary small{opacity:.5}.tm-avatar-category-actions{display:flex;gap:4px}.tm-avatar-category-actions button{width:30px;height:30px;padding:0}',
        '@media(max-width:430px){.tm-avatar-page-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;padding:10px}.tm-avatar-page-notice{margin:8px 10px 0}.tm-avatar-series-track{gap:7px;grid-auto-columns:calc((100% - (var(--tm-avatar-series-cols,3) - 1)*7px)/var(--tm-avatar-series-cols,3))}}'
    ].join(''); }

    ns.createAvatarPage = function (options) {
        options = options || {};
        var doc = options.document || global.document, store = options.store, processor = options.processor, runtime = options.runtime;
        var library = options.library || ns.avatarLibrary, canMutate = options.canMutate || function () { return true; };
        var imageLoaderApi = options.imageLoader, imageToolsApi = options.imageTools || ns.imageTools, getRoot = options.getRoot;
        var closeManager = options.closeManager || function () {}, createSheet = options.createSheet, closeSheet = options.closeSheet || function (sheet) { if (sheet && sheet.parentNode) sheet.parentNode.removeChild(sheet); };
        var createActionDialog = options.createActionDialog, openImageLightbox = options.openImageLightbox, openCategoryPicker = options.openCategoryPicker, openTagPicker = options.openTagPicker;
        var loadUiData = options.loadUiData || function () { return {}; }, saveUiData = options.saveUiData || function () {}, onImportingChange = options.onImportingChange || function () {}, onBatchModeChange = options.onBatchModeChange || function () {}, toast = options.toast || function () {};
        var confirmAction = options.confirm || global.confirm, logger = options.console || global.console || { error: function () {} };
        var mounted = false, root = null, fileInput = null, gridLoader = null, resizeObserver = null, assets = [], refreshToken = 0, importing = false;
        var searchOpen = false, sortOpen = false, query = '', category = '__all__', batchMode = false, batchSelected = new Set(), expandedSeriesId = '', railTimers = new Map(), lastColumnCount = 0, activeAvatarIds = [];
        function data() { var value = loadUiData(); library.ensureState(value); return value; }
        function reportError(stage, error, file) { if (logger && typeof logger.error === 'function') logger.error('[Theme Manager][Avatar] ' + stage, { file: file && file.name, error: error, cause: error && error.cause }); }
        function setNotice(message, kind) { if (!root) return; var notice = root.querySelector('[data-avatar-notice]'); notice.innerHTML = kind === 'loading' && message ? '<i class="fa-solid fa-spinner"></i>' + esc(message) : esc(message || ''); if (kind) notice.setAttribute('data-kind', kind); else notice.removeAttribute('data-kind'); notice.hidden = !message; }
        function persist(value, message) { return Promise.resolve(saveUiData(value)).then(function () { if (message) toast(message); return true; }).catch(function (error) { reportError('metadata save failed', error); setNotice('头像整理信息保存失败，请重试', 'error'); throw error; }); }
        function ensureStyle() { if (doc.getElementById(STYLE_ID)) return; var style = doc.createElement('style'); style.id = STYLE_ID; style.textContent = styleText(); doc.head.appendChild(style); }
        function removeStyle() { var style = doc.getElementById(STYLE_ID); if (style && style.parentNode) style.parentNode.removeChild(style); }
        function friendlyImportError(error) { var code = error && error.code || ''; if (/READ_FAILED/.test(code)) return '图片读取失败'; if (/DECODE_FAILED/.test(code)) return '图片解码失败'; if (code === 'AVATAR_FORMAT_UNSUPPORTED') return '图片格式暂不支持'; if (code === 'AVATAR_STORAGE_QUOTA_EXCEEDED') return '存储空间不足'; if (/^(?:AVATAR_IDB|AVATAR_STORAGE)/.test(code)) return '本地存储失败'; return '未能保存头像'; }
        function setImporting(value) { importing = Boolean(value); onImportingChange(importing); if (root && importing) setNotice('正在添加头像…', 'loading'); }
        function mutationBlocked() { if (canMutate()) return false; setNotice('头像存储当前只读或尚未安全就绪', 'error'); return true; }
        function nativeSlotHtml() { return '<button type="button" class="tm-avatar-native-slot" data-avatar-action="native" aria-label="调整原头像"><i class="fa-regular fa-circle-user" aria-hidden="true"></i></button>'; }
        function activeRank(id) { var index = activeAvatarIds.indexOf(id); return index === -1 ? Number.MAX_SAFE_INTEGER : index; }
        function syncActiveAvatarIds() { var current = runtime && typeof runtime.getActiveAvatarIds === 'function' ? runtime.getActiveAvatarIds() : {}; activeAvatarIds = [current && current.user, current && current.character].filter(function (id, index, list) { return id && list.indexOf(id) === index; }); }
        function cardHtml(asset) { var selected = batchSelected.has(asset.id), active = activeRank(asset.id) !== Number.MAX_SAFE_INTEGER; return '<article class="tm-avatar-page-card' + (active ? ' is-active' : '') + (selected ? ' batch-sel' : '') + '" data-avatar-id="' + esc(asset.id) + '" tabindex="0" role="button" aria-label="使用头像 ' + esc(asset.name) + '"><img class="tm-avatar-page-thumb" src="' + esc(imageLoaderApi.PLACEHOLDER_SRC) + '" data-image-key="' + esc(asset.id) + '" alt="">' + (active ? '<span class="tm-avatar-card-active" title="当前正在使用"><i class="fa-solid fa-check"></i></span>' : '') + '<span class="tm-avatar-card-check"><i class="fa-solid ' + (selected ? 'fa-check' : 'fa-plus') + '"></i></span></article>'; }
        function countGridTracks(value) { value = String(value || '').trim(); if (/^repeat\(\s*auto-(?:fill|fit)/i.test(value)) return 0; var repeat = value.match(/^repeat\(\s*(\d+)/i); if (repeat) return Number(repeat[1]); var depth = 0, count = 0, token = false; value.split('').forEach(function (character) { if (/\s/.test(character) && depth === 0) { if (token) { count += 1; token = false; } return; } token = true; if (character === '(') depth += 1; else if (character === ')' && depth > 0) depth -= 1; }); return count + (token ? 1 : 0); }
        function columns() { var grid = root && root.querySelector('[data-avatar-grid]'), width = grid && grid.clientWidth || 0; if (grid && typeof global.getComputedStyle === 'function') { var template = global.getComputedStyle(grid).gridTemplateColumns, actual = template && template !== 'none' ? countGridTracks(template) : 0; if (actual > 0) return actual; } if (width <= 430) return 3; return Math.max(1, Math.floor((Math.max(112, width - 24) + 9) / 121)); }
        function matchingAssets(state) { var lowered = query.toLocaleLowerCase(), mode = library.ensureState(state).sortMode; var sorted = assets.filter(function (asset) { var meta = library.peekMeta(state, asset.id); if (category !== '__all__' && (category === '__uncategorized__' ? !!meta.category : meta.category !== category)) return false; if (!lowered) return true; var series = library.findSeries(state, asset.id); return [meta.category].concat(meta.tags, series ? [series.name] : []).some(function (text) { return String(text || '').toLocaleLowerCase().indexOf(lowered) !== -1; }); }).sort(function (a, b) { return library.compareAssets(state, a, b, mode); }); var stableIndex = new Map(sorted.map(function (asset, index) { return [asset.id, index]; })); return sorted.sort(function (a, b) { var priority = activeRank(a.id) - activeRank(b.id); return priority || stableIndex.get(a.id) - stableIndex.get(b.id); }); }
        function layoutHtml(state, list, count) { var byId = Object.create(null), emitted = new Set(), chunks = []; list.forEach(function (item) { byId[item.id] = item; }); list.forEach(function (asset) { if (emitted.has(asset.id)) return; var group = library.findSeries(state, asset.id), members = group ? group.members.map(function (id) { return byId[id]; }).filter(Boolean) : []; if (!group || members.length < 2) { emitted.add(asset.id); chunks.push(cardHtml(asset)); return; } members.forEach(function (item) { emitted.add(item.id); }); members.sort(function (a, b) { var priority = activeRank(a.id) - activeRank(b.id); return priority || group.members.indexOf(a.id) - group.members.indexOf(b.id); }); if (members.length <= count) { chunks.push('<section class="tm-avatar-series-inline" data-avatar-series-id="' + esc(group.id) + '" style="--tm-avatar-series-size:' + members.length + '">' + members.map(cardHtml).join('') + '</section>'); return; } var expanded = expandedSeriesId === group.id; chunks.push('<section class="tm-avatar-series-block' + (expanded ? ' is-expanded' : '') + '" data-avatar-series-id="' + esc(group.id) + '" style="--tm-avatar-series-cols:' + count + '"><div class="tm-avatar-series-track">' + members.map(cardHtml).join('') + '</div><div class="tm-avatar-series-controls"><button type="button" class="tm-avatar-series-control" data-avatar-series-manage="' + esc(group.id) + '" title="管理系列" aria-label="管理系列"><i class="fa-solid fa-sliders"></i></button><button type="button" class="tm-avatar-series-control" data-avatar-series-toggle="' + esc(group.id) + '" title="' + (expanded ? '收起系列' : '展开系列') + '" aria-label="' + (expanded ? '收起系列' : '展开系列') + '"><i class="fa-solid ' + (expanded ? 'fa-compress' : 'fa-expand') + '"></i></button></div></section>'); }); return chunks.join(''); }
        function setupGridLoader() { if (gridLoader) gridLoader.disconnect(); var grid = root.querySelector('[data-avatar-grid]'); gridLoader = imageLoaderApi.createImageLoader({ root: grid, rootMargin: '320px 0px', resolveSource: function (id) { return store.getThumbnail(id); } }); gridLoader.observe(grid.querySelectorAll('.tm-avatar-page-thumb')); }
        function renderCategoryBar(state) { var bar = root.querySelector('[data-avatar-catbar]'), categories = library.ensureState(state).categories; bar.innerHTML = [{ key: '__all__', label: '全部' }, { key: '__uncategorized__', label: '未分类' }].concat(categories.map(function (name) { return { key: name, label: name }; })).map(function (item) { return '<button class="tm-catbtn' + (category === item.key ? ' on' : '') + '" data-avatar-category="' + esc(item.key) + '">' + esc(item.label) + '</button>'; }).join(''); }
        function renderBatch() { var area = root.querySelector('[data-avatar-batch-area]'); root.classList.toggle('is-batch', batchMode); onBatchModeChange(batchMode); if (!batchMode) { area.innerHTML = ''; area.style.display = 'none'; return; } area.style.display = ''; area.innerHTML = '<div class="tm-batch-bar"><span class="tm-batch-info">已选 <b>' + batchSelected.size + '</b> 个</span><div class="tm-batch-divider"></div><div class="tm-batch-acts"><button class="tm-batch-btn" data-avatar-batch="all">全选</button><button class="tm-batch-btn" data-avatar-batch="none">取消</button><button class="tm-batch-btn" data-avatar-batch="category"><i class="fa-solid fa-folder"></i> 分类</button><button class="tm-batch-btn" data-avatar-batch="tags"><i class="fa-solid fa-tag"></i> 标签</button><button class="tm-batch-btn" data-avatar-batch="series"><i class="fa-solid fa-layer-group"></i> 系列</button><button class="tm-batch-btn" data-avatar-batch="exit">完成</button></div></div>'; }
        function bindRailInteractions() { root.querySelectorAll('.tm-avatar-series-block').forEach(function (block) { var id = block.dataset.avatarSeriesId; function show() { block.classList.add('is-interacting'); if (railTimers.has(id)) global.clearTimeout(railTimers.get(id)); railTimers.set(id, global.setTimeout(function () { block.classList.remove('is-interacting'); railTimers.delete(id); }, 1700)); } block.addEventListener('pointerdown', show, { passive: true }); block.addEventListener('scroll', show, { passive: true }); block.addEventListener('focusin', show); }); }
        function render() { if (!root) return; syncActiveAvatarIds(); var state = data(), list = matchingAssets(state), grid = root.querySelector('[data-avatar-grid]'), count = columns(); lastColumnCount = count; renderCategoryBar(state); renderBatch(); grid.innerHTML = nativeSlotHtml() + layoutHtml(state, list, count) + (!assets.length ? '<div class="tm-avatar-page-empty">点击底栏中间的＋添加头像</div>' : (!list.length ? '<div class="tm-avatar-page-empty">没有符合条件的头像</div>' : '')); root.querySelectorAll('[data-avatar-sort]').forEach(function (button) { button.classList.toggle('on', button.dataset.avatarSort === library.ensureState(state).sortMode); }); setupGridLoader(); setImporting(importing); bindRailInteractions(); }
        function refresh() { var token = ++refreshToken; return store.listAssets().then(function (items) { if (!mounted || token !== refreshToken) return; assets = items || []; render(); }).catch(function (error) { reportError('library refresh failed', error); if (mounted) setNotice('头像库读取失败', 'error'); throw error; }); }
        function importFiles(files) { if (mutationBlocked()) return Promise.reject(Object.assign(new Error('头像存储当前不可写'), { code: 'AVATAR_STORAGE_READ_ONLY' })); files = Array.prototype.slice.call(files || []); if (!files.length) return Promise.resolve([]); setImporting(true); return Promise.all(files.map(function (file) { return processor.processFile(file).then(function (asset) { return store.putAsset(asset).then(function (saved) { runtime.notifyAssetChanged(saved.id); return { ok: true, asset: saved }; }); }).catch(function (error) { reportError('import failed', error, file); return { ok: false, name: file.name || '未命名图片', error: error }; }); })).then(function (results) { var failed = results.filter(function (item) { return !item.ok; }), passed = results.filter(function (item) { return item.ok; }), orderSave = Promise.resolve(); if (passed.length) { var state = data(); library.assignImportOrders(state, passed.map(function (item) { return item.asset.id; })); orderSave = persist(state); } return orderSave.then(function () { return passed.length ? refresh() : null; }).then(function () { if (failed.length) setNotice(failed.map(function (item) { return item.name + '：' + friendlyImportError(item.error); }).join('；'), 'error'); else setNotice('已添加 ' + passed.length + ' 张头像', 'success'); if (passed.length) toast('✅ 已添加 ' + passed.length + ' 张头像'); return results; }); }).finally(function () { setImporting(false); }); }
        function beginEdit(kind, avatarId, overlay) { if (mutationBlocked()) return; var caps = runtime.getCapabilities(), cap = kind === 'character' ? caps.character : caps.user; if (!caps.themeKey || !cap || !cap.available) { setNotice(!caps.themeKey ? '头像存储暂不可用' : cap && cap.reason || '当前目标不可用'); return; } if (overlay) closeSheet(overlay); if (closeManager() === false) return; global.setTimeout(function () { runtime.beginEdit({ kind: kind, avatarId: avatarId, bindingMode: kind === 'user' ? 'adaptive' : undefined }).catch(function (error) { toast(error.message || '无法启动头像调整', true); }); }, 32); }
        function beginNativeEdit(kind, overlay) { if (mutationBlocked()) return; var cap = runtime.getCapabilities()[kind]; if (!cap || !cap.available) { setNotice(cap && cap.reason || '原头像无法调整'); return; } if (overlay) closeSheet(overlay); closeManager(); global.setTimeout(function () { runtime.beginNativeEdit(kind).catch(function (error) { toast(error.message || '无法启动原头像调整', true); }); }, 32); }
        function dialogItem(action, icon, label, hint, disabled, weak) { return '<button type="button" class="tm-action-dialog-item' + (weak ? ' is-weak' : '') + '" data-avatar-dialog-action="' + action + '"' + (disabled ? ' disabled' : '') + '><i class="fa-solid ' + icon + '"></i><span><strong>' + esc(label) + '</strong>' + (hint ? '<small>' + esc(hint) + '</small>' : '') + '</span></button>'; }
        function openNativeMenu() { var caps = runtime.getCapabilities(), character = caps.character || {}, user = caps.user || {}, overlay = createActionDialog('<div class="tm-action-dialog-title"><i class="fa-regular fa-circle-user"></i>调整原头像</div><div class="tm-action-dialog-list">' + dialogItem('native-user', 'fa-user', '调整 User 原头像', user.reason, !canMutate() || !user.available) + dialogItem('native-character', 'fa-address-card', '调整当前角色原头像', character.reason, !canMutate() || !character.available) + '</div>'); overlay.addEventListener('click', function (event) { var button = event.target.closest('[data-avatar-dialog-action]'); if (!button || button.disabled) return; beginNativeEdit(button.dataset.avatarDialogAction === 'native-user' ? 'user' : 'character', overlay); }); return Promise.resolve(overlay); }
        function viewAsset(id) { if (typeof openImageLightbox !== 'function') return Promise.reject(new Error('大图查看器不可用')); return store.getAsset(id).then(function (asset) { if (!asset || !asset.imageData) throw new Error('头像主图不存在'); openImageLightbox([{ key: asset.id, label: asset.name, source: asset.imageData }], asset.id); return asset; }); }
        function openAssetMenu(id) { var asset = assets.find(function (item) { return item.id === id; }); if (!asset) return Promise.reject(new Error('头像不存在')); var caps = runtime.getCapabilities(), character = caps.character || {}, user = caps.user || {}, overlay = createActionDialog('<div class="tm-action-dialog-title"><i class="fa-solid fa-user"></i>使用这张头像</div><div class="tm-action-dialog-list">' + dialogItem('apply-user', 'fa-user', '设为 User 头像', user.reason, !canMutate() || !user.available) + dialogItem('apply-character', 'fa-address-card', '设为当前角色头像', character.reason, !canMutate() || !character.available) + dialogItem('view', 'fa-expand', '查看完整大图', '', false) + '<div class="tm-action-dialog-divider"></div>' + dialogItem('manage', 'fa-sliders', '管理头像', '分类、标签、系列与删除', false, true) + '</div>'); overlay.addEventListener('click', function (event) { var button = event.target.closest('[data-avatar-dialog-action]'); if (!button || button.disabled) return; var action = button.dataset.avatarDialogAction; if (action === 'apply-user') beginEdit('user', id, overlay); else if (action === 'apply-character') beginEdit('character', id, overlay); else if (action === 'view') { closeSheet(overlay); viewAsset(id).catch(function (error) { setNotice(error.message, 'error'); }); } else if (action === 'manage') { closeSheet(overlay); openManageSheet(id); } }); return Promise.resolve(overlay); }
        function pickerSummary(icon, title, value, action) { return '<button type="button" class="tm-picker-trigger" data-avatar-manage="' + action + '"><span class="tm-picker-trigger-icon"><i class="fa-solid ' + icon + '"></i></span><span class="tm-picker-trigger-copy"><strong>' + esc(title) + '</strong><small>' + esc(value || '未设置') + '</small></span><i class="fa-solid fa-chevron-right tm-picker-trigger-chevron"></i></button>'; }
        function openManageSheet(id) { var asset = assets.find(function (item) { return item.id === id; }); if (!asset) return; var state = data(), meta = library.peekMeta(state, id), series = library.findSeries(state, id); store.getThumbnail(id).then(function (src) { var sheet = createSheet('<div class="tm-sheet-title"><i class="fa-solid fa-sliders"></i>管理头像</div><div class="tm-avatar-manage-summary"><img class="tm-avatar-manage-thumb" src="' + esc(src) + '" alt=""><span><strong>头像资源</strong><small>只整理关系与标注，不修改图片</small></span></div>' + pickerSummary('fa-folder', '分类', meta.category || '无分类', 'category') + pickerSummary('fa-tags', '标签', meta.tags.join('、') || '无标签', 'tags') + pickerSummary('fa-layer-group', '系列', series ? series.name : '未加入系列', 'series') + '<div class="tm-divider"></div><button class="tm-btn tm-btn-danger" data-avatar-manage="delete" style="width:100%"><i class="fa-solid fa-trash"></i> 删除头像</button>'); sheet.addEventListener('click', function (event) { var button = event.target.closest('[data-avatar-manage]'); if (!button) return; var action = button.dataset.avatarManage; if (action === 'category') openCategoryPicker({ categories: library.ensureState(data()).categories, selected: library.peekMeta(data(), id).category, allowClear: true, title: '选择头像分类', onSelect: function (value) { var next = data(); library.ensureMeta(next, id).category = value; persist(next).then(function () { closeSheet(sheet); render(); openManageSheet(id); }); } }); else if (action === 'tags') openTagPicker({ knownTags: library.listTags(data()), selectedTags: library.peekMeta(data(), id).tags, allowClear: true, title: '管理头像标签', onApply: function (values) { var next = data(); library.ensureMeta(next, id).tags = values; persist(next).then(function () { closeSheet(sheet); render(); openManageSheet(id); }); } }); else if (action === 'series') { closeSheet(sheet); var owner = library.findSeries(data(), id); if (owner) openSeriesManageSheet(owner.id); else openJoinSeriesSheet(id); } else if (action === 'delete') deleteAvatar(id, sheet); }); }); }
        function deleteAvatar(id, sheet) { if (mutationBlocked() || !confirmAction('确定删除这张头像吗？使用它的绑定会同时清理。')) return; runtime.deleteAsset(id).then(function () { var state = data(); library.removeAssetReferences(state, id); return persist(state); }).then(function () { if (sheet) closeSheet(sheet); toast('已删除头像并清理相关绑定'); return refresh(); }).catch(function (error) { setNotice('删除失败：' + error.message, 'error'); }); }
        function openJoinSeriesSheet(id) { var groups = Object.values(library.ensureState(data()).series.groups); if (!groups.length) { toast('请先通过批量整理创建系列', true); return; } var sheet = createSheet('<div class="tm-sheet-title"><i class="fa-solid fa-layer-group"></i>加入系列</div>' + groups.map(function (group) { return '<button class="tm-picker-row" data-avatar-join-series="' + esc(group.id) + '"><span><i class="fa-solid fa-layer-group"></i><strong>' + esc(group.name) + '</strong></span><i class="fa-solid fa-plus"></i></button>'; }).join('')); sheet.addEventListener('click', function (event) { var button = event.target.closest('[data-avatar-join-series]'); if (!button) return; var state = data(), result = library.addMember(state, button.dataset.avatarJoinSeries, id); if (!result.ok) { toast('无法加入该系列', true); return; } persist(state, '已加入系列').then(function () { closeSheet(sheet); render(); }); }); }
        function openSeriesManageSheet(seriesId) {
            var state = data(), group = library.ensureState(state).series.groups[seriesId];
            if (!group) return;
            var sheet = createSheet('<div class="tm-sheet-title"><i class="fa-solid fa-layer-group"></i>管理头像系列</div><div class="tm-field"><label>系列名称</label><input type="text" data-avatar-series-name maxlength="80" value="' + esc(group.name) + '"></div><div class="tm-series-member-list">' + group.members.map(function (id, index) {
                return '<div class="tm-series-member-row"><i class="fa-solid fa-user"></i><div><strong>头像</strong><small>' + esc(id) + '</small></div><button class="tm-btn-sm" data-avatar-series-up="' + esc(id) + '" title="前移" aria-label="前移成员"' + (index === 0 ? ' disabled' : '') + '><i class="fa-solid fa-arrow-up"></i></button><button class="tm-btn-sm" data-avatar-series-down="' + esc(id) + '" title="后移" aria-label="后移成员"' + (index === group.members.length - 1 ? ' disabled' : '') + '><i class="fa-solid fa-arrow-down"></i></button><button class="tm-btn-sm tm-series-member-remove" data-avatar-series-remove="' + esc(id) + '" title="移出系列" aria-label="移出系列"><i class="fa-solid fa-xmark"></i></button></div>';
            }).join('') + '</div><div class="tm-edit-foot tm-series-manage-actions"><button class="tm-btn tm-btn-danger" data-avatar-series-dissolve>解散系列</button><span></span><button class="tm-btn tm-btn-outline" data-avatar-series-cancel>取消</button><button class="tm-btn tm-btn-safe" data-avatar-series-save>保存修改</button></div>');
            sheet.addEventListener('click', function (event) {
                if (event.target.closest('[data-avatar-series-cancel]')) closeSheet(sheet);
                else if (event.target.closest('[data-avatar-series-save]')) {
                    var next = data(), current = library.ensureState(next).series.groups[seriesId], name = sheet.querySelector('[data-avatar-series-name]').value.trim();
                    if (!name) { toast('请输入系列名称', true); return; }
                    current.name = name;
                    persist(next, '已保存系列').then(function () { closeSheet(sheet); render(); });
                } else if (event.target.closest('[data-avatar-series-dissolve]')) {
                    if (!confirmAction('解散系列？头像图片会全部保留。')) return;
                    var nextD = data(); library.dissolveSeries(nextD, seriesId);
                    persist(nextD, '已解散系列').then(function () { closeSheet(sheet); render(); });
                } else {
                    var up = event.target.closest('[data-avatar-series-up]'), down = event.target.closest('[data-avatar-series-down]'), remove = event.target.closest('[data-avatar-series-remove]');
                    if (up || down) {
                        var nextM = data(), moved = library.moveMember(nextM, seriesId, (up || down).getAttribute(up ? 'data-avatar-series-up' : 'data-avatar-series-down'), up ? -1 : 1);
                        if (!moved.ok) return;
                        persist(nextM).then(function () { closeSheet(sheet); render(); openSeriesManageSheet(seriesId); });
                        return;
                    }
                    if (!remove) return;
                    var nextR = data(), result = library.removeMember(nextR, seriesId, remove.dataset.avatarSeriesRemove);
                    persist(nextR, result.dissolved ? '成员不足两张，系列已自动解散' : '已移出系列').then(function () { closeSheet(sheet); render(); if (!result.dissolved) openSeriesManageSheet(seriesId); });
                }
            });
        }
        function createSeriesFromSelection() { var state = data(), sorted = assets.slice().sort(function (a, b) { return library.compareAssets(state, a, b, library.ensureState(state).sortMode); }), ids = sorted.filter(function (asset) { return batchSelected.has(asset.id); }).map(function (asset) { return asset.id; }); if (ids.length < 2) { toast('请至少选择两张头像', true); return; } if (ids.some(function (id) { return !!library.findSeries(state, id); })) { toast('所选头像中已有系列成员，请先移出原系列', true); return; } var sheet = createSheet('<div class="tm-sheet-title"><i class="fa-solid fa-layer-group"></i>创建头像系列</div><div class="tm-field"><label>系列名称</label><input type="text" data-avatar-new-series maxlength="80" placeholder="例如：情侣头像"></div><div class="tm-hint">成员顺序按当前显示顺序保存，之后可在系列管理中调整。</div><div class="tm-edit-foot"><button class="tm-btn tm-btn-outline" data-avatar-series-cancel>取消</button><button class="tm-btn tm-btn-safe" data-avatar-series-create>创建系列</button></div>'); sheet.querySelector('[data-avatar-series-cancel]').addEventListener('click', function () { closeSheet(sheet); }); sheet.querySelector('[data-avatar-series-create]').addEventListener('click', function () { var name = sheet.querySelector('[data-avatar-new-series]').value.trim(), next = data(), result = library.createSeries(next, name, ids); if (!result.ok) { toast(name ? '无法创建系列' : '请输入系列名称', true); return; } persist(next, '已创建系列').then(function () { closeSheet(sheet); batchSelected.clear(); batchMode = false; render(); }); }); }
        function applyBatchCategory() { if (!batchSelected.size) { toast('请先选择头像', true); return; } openCategoryPicker({ categories: library.ensureState(data()).categories, allowClear: true, title: '批量设置分类', onSelect: function (value) { var state = data(); batchSelected.forEach(function (id) { library.ensureMeta(state, id).category = value; }); persist(state, '已批量更新分类').then(render); } }); }
        function applyBatchTags() { if (!batchSelected.size) { toast('请先选择头像', true); return; } openTagPicker({ knownTags: library.listTags(data()), requireSelection: true, title: '批量添加标签', onApply: function (values) { var state = data(); batchSelected.forEach(function (id) { var meta = library.ensureMeta(state, id); meta.tags = Array.from(new Set(meta.tags.concat(values))); }); persist(state, '已批量添加标签').then(render); } }); }
        function handleClick(event) { var native = event.target.closest('[data-avatar-action="native"]'); if (native) { openNativeMenu(); return; } var manage = event.target.closest('[data-avatar-series-manage]'); if (manage) { event.stopPropagation(); openSeriesManageSheet(manage.dataset.avatarSeriesManage); return; } var toggle = event.target.closest('[data-avatar-series-toggle]'); if (toggle) { event.stopPropagation(); expandedSeriesId = expandedSeriesId === toggle.dataset.avatarSeriesToggle ? '' : toggle.dataset.avatarSeriesToggle; render(); return; } var cat = event.target.closest('[data-avatar-category]'); if (cat) { category = cat.dataset.avatarCategory; render(); return; } var sort = event.target.closest('[data-avatar-sort]'); if (sort) { var state = data(); library.ensureState(state).sortMode = sort.dataset.avatarSort; persist(state).then(render); return; } var batch = event.target.closest('[data-avatar-batch]'); if (batch) { var action = batch.dataset.avatarBatch; if (action === 'all') assets.forEach(function (asset) { batchSelected.add(asset.id); }); else if (action === 'none') batchSelected.clear(); else if (action === 'exit') { batchMode = false; batchSelected.clear(); } else if (action === 'category') { applyBatchCategory(); return; } else if (action === 'tags') { applyBatchTags(); return; } else if (action === 'series') { createSeriesFromSelection(); return; } render(); return; } var card = event.target.closest('.tm-avatar-page-card'); if (!card || !root.contains(card)) return; var id = card.dataset.avatarId; if (batchMode) { if (batchSelected.has(id)) batchSelected.delete(id); else batchSelected.add(id); render(); } else openAssetMenu(id).catch(function (error) { setNotice(error.message || '头像操作无法打开', 'error'); }); }
        function handleKeydown(event) { if (event.key !== 'Enter' && event.key !== ' ') return; var target = event.target.closest('.tm-avatar-page-card,.tm-avatar-native-slot'); if (!target) return; event.preventDefault(); target.click(); }
        function handleFileChange(event) { var input = event.currentTarget || fileInput, files = imageToolsApi.snapshotInputFiles(input); if (!files.length) return; var pending = importFiles(files); input.value = ''; pending.catch(function (error) { reportError('file input import rejected', error); }); }
        function mount() { if (mounted) return refresh(); root = getRoot(); if (!root) return Promise.reject(new Error('头像管理页面不存在')); mounted = true; ensureStyle(); fileInput = root.querySelector('[data-avatar-file]'); root.addEventListener('click', handleClick); root.addEventListener('keydown', handleKeydown); fileInput.addEventListener('change', handleFileChange); var search = root.querySelector('[data-avatar-search]'); search.addEventListener('input', function () { query = search.value.trim(); render(); }); root.querySelector('[data-avatar-search-clear]').addEventListener('click', function () { query = ''; search.value = ''; render(); search.focus(); }); if (global.ResizeObserver) { resizeObserver = new global.ResizeObserver(function () { var next = columns(); if (next !== lastColumnCount) render(); }); resizeObserver.observe(root.querySelector('[data-avatar-grid]')); } return refresh(); }
        function unmount() { if (!mounted) return; mounted = false; refreshToken++; if (gridLoader) gridLoader.disconnect(); if (resizeObserver) resizeObserver.disconnect(); railTimers.forEach(function (timer) { global.clearTimeout(timer); }); railTimers.clear(); root.removeEventListener('click', handleClick); root.removeEventListener('keydown', handleKeydown); fileInput.removeEventListener('change', handleFileChange); fileInput = null; root = null; removeStyle(); }
        function toggleSearch() { if (!root) return false; searchOpen = !searchOpen; var bar = root.querySelector('[data-avatar-search-bar]'); bar.classList.toggle('open', searchOpen); if (searchOpen) root.querySelector('[data-avatar-search]').focus(); else { query = ''; root.querySelector('[data-avatar-search]').value = ''; render(); } return searchOpen; }
        function toggleSort() { if (!root) return false; sortOpen = !sortOpen; root.querySelector('[data-avatar-sortbar]').classList.toggle('open', sortOpen); return sortOpen; }
        function enterBatchMode() { if (!root) return false; batchMode = true; batchSelected.clear(); render(); return true; }
        function toggleBatchMode() { if (!root) return false; batchMode = !batchMode; batchSelected.clear(); render(); return batchMode; }
        function openCategoryRenameSheet(name, parentSheet) {
            var sheet = createSheet('<div class="tm-sheet-title"><i class="fa-solid fa-pen"></i>重命名分类</div><div class="tm-field"><label>分类名称</label><input type="text" data-avatar-category-rename maxlength="80" value="' + esc(name) + '"></div><div class="tm-edit-foot"><button class="tm-btn tm-btn-outline" data-avatar-category-rename-cancel>取消</button><button class="tm-btn tm-btn-safe" data-avatar-category-rename-save>保存</button></div>');
            sheet.querySelector('[data-avatar-category-rename-cancel]').addEventListener('click', function () { closeSheet(sheet); });
            sheet.querySelector('[data-avatar-category-rename-save]').addEventListener('click', function () {
                var nextName = sheet.querySelector('[data-avatar-category-rename]').value.trim(), state = data(), result = library.renameCategory(state, name, nextName);
                if (!result.ok) { toast(result.reason === 'collision' ? '已有同名分类' : '请输入有效的分类名称', true); return; }
                persist(state, '已重命名分类').then(function () { closeSheet(sheet); if (parentSheet) closeSheet(parentSheet); render(); openCategoryManager(); });
            });
            return sheet;
        }
        function openCategoryManager() {
            var state = data(), counts = Object.create(null);
            assets.forEach(function (asset) { var cat = library.peekMeta(state, asset.id).category; if (cat) counts[cat] = (counts[cat] || 0) + 1; });
            var categories = library.ensureState(state).categories;
            var sheet = createSheet('<div class="tm-sheet-title"><i class="fa-solid fa-tags"></i>头像分类管理</div>' + (categories.length ? categories.map(function (name, index) {
                return '<div class="tm-cat-item"><span class="tm-cat-name">' + esc(name) + '</span><span class="tm-cat-count">' + (counts[name] || 0) + '个</span><span class="tm-avatar-category-actions"><button class="tm-btn-sm" data-avatar-cat-rename="' + index + '" title="重命名" aria-label="重命名分类"><i class="fa-solid fa-pen"></i></button><button class="tm-btn-sm" data-avatar-cat-up="' + index + '" title="上移" aria-label="上移分类"><i class="fa-solid fa-arrow-up"></i></button><button class="tm-btn-sm" data-avatar-cat-down="' + index + '" title="下移" aria-label="下移分类"><i class="fa-solid fa-arrow-down"></i></button><button class="tm-btn-sm" data-avatar-cat-delete="' + index + '" title="删除" aria-label="删除分类"><i class="fa-solid fa-trash"></i></button></span></div>';
            }).join('') : '<div class="tm-empty"><i class="fa-solid fa-tags"></i><span>还没有分类</span></div>') + '<div class="tm-divider"></div><div class="tm-cat-add-row"><input type="text" data-avatar-new-category placeholder="新分类名称…"><button class="tm-btn tm-btn-safe" data-avatar-category-add>添加</button></div>');
            sheet.addEventListener('click', function (event) {
                var current = data(), list = library.ensureState(current).categories.slice(), add = event.target.closest('[data-avatar-category-add]');
                if (add) {
                    var name = sheet.querySelector('[data-avatar-new-category]').value.trim();
                    if (!name || library.isReservedCategoryName(name) || list.indexOf(name) !== -1) { toast('分类名称为空、保留或已存在', true); return; }
                    library.ensureState(current).categories.push(name);
                } else {
                    var rename = event.target.closest('[data-avatar-cat-rename]'), up = event.target.closest('[data-avatar-cat-up]'), down = event.target.closest('[data-avatar-cat-down]'), del = event.target.closest('[data-avatar-cat-delete]');
                    if (rename) { openCategoryRenameSheet(list[Number(rename.dataset.avatarCatRename)], sheet); return; }
                    if (up) { var i = Number(up.dataset.avatarCatUp); if (i < 1) return; list.splice(i - 1, 0, list.splice(i, 1)[0]); library.ensureState(current).categories = list; }
                    else if (down) { var j = Number(down.dataset.avatarCatDown); if (j >= list.length - 1) return; list.splice(j + 1, 0, list.splice(j, 1)[0]); library.ensureState(current).categories = list; }
                    else if (del) { var target = list[Number(del.dataset.avatarCatDelete)]; if (!confirmAction('删除分类「' + target + '」？头像会变为未分类。')) return; library.deleteCategory(current, target); }
                    else return;
                }
                persist(current).then(function () { closeSheet(sheet); render(); openCategoryManager(); });
            });
            return sheet;
        }
        return { mount: mount, unmount: unmount, refresh: refresh, importFiles: importFiles, pickFiles: function () { if (!mounted || !fileInput || importing || mutationBlocked()) return false; fileInput.click(); return true; }, beginNativeEdit: beginNativeEdit, openNativeMenu: openNativeMenu, openAssetMenu: openAssetMenu, viewAsset: viewAsset, toggleSearch: toggleSearch, toggleSort: toggleSort, enterBatchMode: enterBatchMode, toggleBatchMode: toggleBatchMode, openCategoryManager: openCategoryManager, getNativeStatus: function (kind) { kind = kind === 'user' ? 'user' : 'character'; var cap = runtime.getCapabilities()[kind] || {}; return { available: !!cap.available, reason: cap.reason || '', label: cap.target && cap.target.label || '', targetKey: cap.target && cap.target.key || '' }; }, getState: function () { var state = data(); return { mounted: mounted, count: assets.length, importing: importing, batchMode: batchMode, categories: library.ensureState(state).categories.length, series: Object.keys(library.ensureState(state).series.groups).length }; } };
    };
    ns.avatarPage = { buildPageHtml: buildPageHtml, styleText: styleText };
})(window);
