(function (global) {
    var ns = global.ThemeMgrModules = global.ThemeMgrModules || {};

    ns.injectStyles = function () {
        var old = document.getElementById('tm-style');
        if (old) old.parentNode.removeChild(old);
        var s = document.createElement('style');
        s.id = 'tm-style';
        s.textContent = [
            '@keyframes tm-fadein{from{opacity:0}to{opacity:1}}',
            '@keyframes tm-sheet-up{from{transform:translateY(100%)}to{transform:translateY(0)}}',
            '@keyframes tm-popin{from{opacity:0;transform:scale(.95)}to{opacity:1;transform:scale(1)}}',
            '@keyframes tm-spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}',
            '.tm-light{--tm-bg:#f5f5f7;--tm-bg2:#ececef;--tm-text:#111;--tm-border:rgba(0,0,0,.1);--tm-card-bg:rgba(0,0,0,.04);--tm-card-border:transparent;--tm-head-bg:rgba(255,255,255,.8);--tm-control-bg:rgba(0,0,0,.06);--tm-control-hover:rgba(0,0,0,.12);--tm-control-border:rgba(0,0,0,.15);--tm-shadow:rgba(0,0,0,.25);--tm-accent-text:#fff;}',
            '.tm-dark{--tm-bg:#16161a;--tm-bg2:#1e1e24;--tm-text:#eee;--tm-border:rgba(255,255,255,.08);--tm-card-bg:rgba(255,255,255,.05);--tm-card-border:transparent;--tm-head-bg:rgba(0,0,0,.3);--tm-control-bg:rgba(255,255,255,.06);--tm-control-hover:rgba(255,255,255,.14);--tm-control-border:rgba(255,255,255,.15);--tm-shadow:rgba(0,0,0,.35);--tm-accent-text:#fff;}',
            '.tm-overlay{position:fixed;top:0;left:0;right:0;bottom:0;width:100vw;height:100dvh;z-index:2147483647;',
            'background:var(--tm-bg,var(--SmartThemeBackgroundColor,#16161a));',
            'color:var(--tm-text,var(--SmartThemeBodyColor,#eee));',
            'display:flex;flex-direction:column;overflow:hidden;animation:tm-fadein .18s ease;font-size:14px;font-family:var(--tm-theme-font,inherit);isolation:isolate;}',
            '.tm-overlay::before{content:"";position:absolute;inset:-4px;z-index:0;pointer-events:none;background-image:var(--tm-theme-bg-image,none);background-size:var(--tm-theme-bg-size,cover);background-position:var(--tm-theme-bg-position,center);background-repeat:var(--tm-theme-bg-repeat,no-repeat);opacity:0;transition:opacity .2s;filter:blur(2px) saturate(.92);}',
            '.tm-overlay.tm-follow::before{opacity:var(--tm-theme-bg-opacity,.28);}',
            '.tm-overlay::after{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;background-image:var(--tm-theme-manager-image,none);background-size:var(--tm-theme-manager-size,cover);background-position:var(--tm-theme-manager-position,center);background-repeat:var(--tm-theme-manager-repeat,no-repeat);opacity:0;transition:opacity .2s;filter:saturate(.92);}',
            '.tm-overlay.tm-follow.tm-has-manager-background::after{opacity:var(--tm-theme-manager-opacity,.96);}',
            '.tm-box{position:relative;z-index:1;width:100%;height:100%;min-height:0;display:flex;flex-direction:column;overflow:hidden;}',
            '.tm-head{position:relative;overflow:hidden;display:flex;align-items:center;gap:8px;padding:12px 15px;padding-top:max(12px, env(safe-area-inset-top, 12px));flex-shrink:0;border-bottom:1px solid var(--tm-border,rgba(127,127,127,.1));background:var(--tm-head-bg,rgba(0,0,0,.12));backdrop-filter:var(--tm-panel-blur,blur(14px));box-shadow:var(--tm-panel-shadow,none);}',
            '.tm-head::before,.tm-bottombar::before{content:"";position:absolute;inset:0;z-index:0;pointer-events:none;opacity:0;}',
            '.tm-head>* ,.tm-bottombar>*{position:relative;z-index:1;}',
            '.tm-head-title{font-weight:700;font-size:1.05em;display:flex;align-items:center;gap:7px;flex:1;min-width:0;}',
            '.tm-head-title i{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-head-name{min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-head-actions{display:flex;align-items:center;gap:4px;}',
            '.tm-head-title-switcher{height:34px;padding:0 6px 0 0;border:0;border-radius:var(--tm-control-radius,8px);background:transparent;color:inherit;font-family:inherit;text-align:left;cursor:pointer;white-space:nowrap;transition:background .16s,color .16s;}',
            '.tm-head-title-switcher:hover,.tm-head-title-switcher.open{background:var(--tm-control-bg,rgba(127,127,127,.06));}',
            '.tm-head-title-switcher:focus-visible{outline:2px solid var(--SmartThemeQuoteColor,#7c6daf);outline-offset:1px;}',
            '.tm-page-switcher-icon{color:var(--SmartThemeQuoteColor,#7c6daf);font-size:.94em;flex-shrink:0;}',
            '.tm-page-switcher-chevron{font-size:.68em;opacity:.52;transition:transform .16s;flex-shrink:0;}',
            '.tm-head-title-switcher.open .tm-page-switcher-chevron{transform:rotate(180deg);}',
            '.tm-page-menu{position:absolute;width:160px;max-width:calc(100vw - 16px);padding:6px;display:flex;flex-direction:column;gap:2px;box-sizing:border-box;border:1px solid var(--tm-control-border,rgba(127,127,127,.16));border-radius:var(--tm-panel-radius,12px);background:var(--tm-bg2,var(--SmartThemeBackgroundColor,#1e1e24));color:var(--tm-text,var(--SmartThemeBodyColor,#eee));box-shadow:0 10px 30px var(--tm-shadow,rgba(0,0,0,.3));backdrop-filter:var(--tm-panel-blur,blur(14px));pointer-events:auto;z-index:4;transform-origin:top left;animation:tm-popin .14s ease;}',
            '.tm-page-menu[hidden]{display:none !important;}',
            '.tm-page-menu-item{width:100%;min-height:40px;padding:7px 10px;display:grid;grid-template-columns:18px minmax(0,1fr) 16px;align-items:center;gap:8px;border:0;border-radius:var(--tm-control-radius,8px);background:transparent;color:inherit;font:inherit;font-size:.84em;text-align:left;cursor:pointer;opacity:.72;}',
            '.tm-page-menu-item:hover,.tm-page-menu-item:focus-visible{opacity:1;background:var(--tm-control-hover,rgba(127,127,127,.12));outline:none;}',
            '.tm-page-menu-item.active{opacity:1;background:color-mix(in srgb,var(--SmartThemeQuoteColor,#7c6daf) 12%,transparent);}',
            '.tm-page-menu-icon{color:var(--SmartThemeQuoteColor,#7c6daf);text-align:center;}',
            '.tm-page-menu-check{color:var(--SmartThemeQuoteColor,#7c6daf);opacity:0;font-size:.76em;}',
            '.tm-page-menu-item.active .tm-page-menu-check{opacity:.85;}',
            '.tm-app-pages{flex:1;min-width:0;min-height:0;display:flex;overflow:hidden;}',
            '.tm-app-page{flex:1;min-width:0;min-height:0;overflow:hidden;}',
            '.tm-app-page[hidden]{display:none !important;}',
            '.tm-app-page-themes{display:flex;flex-direction:column;}',
            '.tm-app-page-avatars,.tm-app-page-backgrounds{display:grid;place-items:center;overflow-y:auto;padding:20px;box-sizing:border-box;}',
            '.tm-app-placeholder{width:min(100%,360px);display:flex;flex-direction:column;align-items:center;text-align:center;gap:7px;padding:28px 20px;border:1px dashed var(--tm-control-border,rgba(127,127,127,.18));border-radius:var(--tm-panel-radius,16px);background:var(--tm-control-bg,rgba(127,127,127,.05));box-sizing:border-box;}',
            '.tm-app-placeholder>i{font-size:2em;color:var(--SmartThemeQuoteColor,#7c6daf);opacity:.72;margin-bottom:4px;}',
            '.tm-app-placeholder h2{font-size:1.05em;margin:0;color:inherit;}',
            '.tm-app-placeholder p{font-size:.82em;line-height:1.55;margin:0;opacity:.58;}',
            '.tm-overlay:not([data-tm-active-page="themes"]) .tm-themes-only{display:none !important;}',
            '.tm-overlay:not([data-tm-active-page="themes"]) .tm-bottombar{justify-content:flex-end;}',
            '#tm-bottom-settings{margin-left:auto;}',
            '.tm-auto-hide-head .tm-head{cursor:pointer;}',
            '.tm-auto-hide-head .tm-head-title-switcher,.tm-auto-hide-head .tm-head-actions{transition:opacity .18s ease,transform .18s ease,visibility .18s;}',
            '.tm-auto-hide-head:not(.tm-head-revealed) .tm-head-title-switcher,.tm-auto-hide-head:not(.tm-head-revealed) .tm-head-actions{opacity:0;visibility:hidden;pointer-events:none;transform:translateY(-4px);}',
            '.tm-icon-btn{cursor:pointer;background:none;border:none;opacity:.55;font-size:1.15em;',
            'width:34px;height:34px;border-radius:var(--tm-control-radius,50%);display:flex;align-items:center;justify-content:center;transition:.18s;color:inherit;box-shadow:var(--tm-control-shadow,none);flex-shrink:0;}',
            '.tm-icon-btn:hover{opacity:1;background:var(--tm-control-hover,rgba(127,127,127,.12));color:var(--SmartThemeQuoteColor,#7c6daf);}',
'.tm-search-bar{display:none;padding:8px 15px;border-bottom:1px solid var(--tm-border,rgba(127,127,127,.08));background:var(--tm-head-bg,rgba(0,0,0,.06));flex-shrink:0;}',
            '.tm-search-bar.open{display:flex;align-items:center;gap:8px;}',
            '.tm-search-wrap{flex:1;position:relative;display:flex;align-items:center;}',
            '.tm-search-wrap i{position:absolute;left:10px;opacity:.4;font-size:.85em;pointer-events:none;}',
            '.tm-search-inp{width:100%;background:var(--tm-control-bg,rgba(127,127,127,.08));border:var(--tm-control-border-style,1px solid var(--tm-control-border,rgba(127,127,127,.2)));border-radius:var(--tm-control-radius,8px);color:inherit;padding:7px 32px 7px 30px;font-size:.85em;font-family:inherit;box-sizing:border-box;}',
            '.tm-search-inp:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-search-clear{background:none;border:none;color:inherit;opacity:.4;cursor:pointer;font-size:.9em;padding:4px;line-height:1;}',
            '.tm-search-clear:hover{opacity:.9;}',
            '.tm-catbar{display:flex;gap:6px;padding:8px 15px;overflow-x:auto;flex-wrap:nowrap;flex-shrink:0;-webkit-overflow-scrolling:touch;scrollbar-width:none;border-bottom:1px solid var(--tm-border,rgba(127,127,127,.08));background:color-mix(in srgb,var(--tm-head-bg,transparent) 72%,transparent);cursor:grab;}',
            '.tm-catbar.dragging{cursor:grabbing;}',
            '.tm-catbar::-webkit-scrollbar{display:none;}',
            '.tm-catbtn{padding:5px 14px;border-radius:var(--tm-control-radius,18px);font-size:.78em;cursor:pointer;white-space:nowrap;flex-shrink:0;border:var(--tm-control-border-style,1px solid var(--tm-control-border,rgba(127,127,127,.15)));background:var(--tm-control-bg,rgba(127,127,127,.06));box-shadow:var(--tm-control-shadow,none);transition:all .15s;color:inherit;font-family:inherit;}',
            '.tm-catbtn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-catbtn.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:var(--tm-accent-text,#fff);border-color:var(--SmartThemeQuoteColor,#7c6daf);font-weight:600;}',
            '.tm-sortbar{display:none;padding:6px 15px;border-bottom:1px solid var(--tm-border,rgba(127,127,127,.08));background:color-mix(in srgb,var(--tm-head-bg,transparent) 55%,transparent);flex-shrink:0;gap:6px;align-items:center;overflow-x:auto;scrollbar-width:none;}',
            '.tm-sortbar.open{display:flex;}',
            '.tm-sortbar::-webkit-scrollbar{display:none;}',
            '.tm-sort-chip{padding:4px 12px;border-radius:var(--tm-control-radius,14px);font-size:.72em;cursor:pointer;white-space:nowrap;flex-shrink:0;border:var(--tm-control-border-style,1px solid var(--tm-control-border,rgba(127,127,127,.12)));background:var(--tm-control-bg,rgba(127,127,127,.04));box-shadow:var(--tm-control-shadow,none);transition:all .15s;color:inherit;font-family:inherit;}',
            '.tm-sort-chip:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-sort-chip.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:var(--tm-accent-text,#fff);border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-sort-divider{width:1px;height:18px;background:rgba(127,127,127,.18);flex-shrink:0;margin:0 2px;}',
            '.tm-grid-size-label{font-size:.72em;opacity:.4;flex-shrink:0;white-space:nowrap;}',
            '.tm-grid-size-btn{width:26px;height:26px;border-radius:var(--tm-control-radius,50%);border:var(--tm-control-border-style,1px solid var(--tm-control-border,rgba(127,127,127,.16)));background:var(--tm-control-bg,rgba(127,127,127,.06));color:inherit;box-shadow:var(--tm-control-shadow,none);cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:.72em;transition:.15s;flex-shrink:0;}',
            '.tm-grid-size-btn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.12);}',
            '.tm-grid-area{flex:1;overflow-y:auto;padding:12px 12px 8px;}',
            '.tm-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(var(--tm-grid-card-min,108px),1fr));gap:9px;}',
            '.tm-series-block{grid-column:1/-1;min-width:0;position:relative;margin:2px 0 3px;padding:0;background:transparent;box-shadow:none;overflow:visible;}',
            '.tm-series-head{height:44px;display:flex;align-items:center;gap:5px;padding-left:4px;border-bottom:1px solid rgba(127,127,127,.08);}',
            '.tm-series-manage{min-width:0;flex:1;height:100%;display:flex;align-items:center;gap:7px;padding:0 8px;border:0;background:transparent;color:inherit;font-family:inherit;text-align:left;cursor:pointer;}',
            '.tm-series-manage>i{color:var(--SmartThemeQuoteColor,#7c6daf);opacity:.62;flex-shrink:0;}',
            '.tm-series-manage>span{min-width:0;font-size:.84em;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-series-manage>small{font-size:.68em;opacity:.45;white-space:nowrap;flex-shrink:0;}',
            '.tm-series-manage:hover>span{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-series-toggle{width:44px;height:44px;display:grid;place-items:center;flex-shrink:0;border:0;border-left:1px solid rgba(127,127,127,.08);background:transparent;color:inherit;opacity:.72;cursor:pointer;font-size:.78em;}',
            '.tm-series-toggle:hover{color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.06);opacity:1;}',
            '.tm-series-toggle i{transition:transform .2s ease;}',
            '.tm-series-block.is-expanded .tm-series-toggle i{transform:rotate(180deg);}',
            '.tm-series-track{display:grid;grid-auto-flow:column;grid-auto-columns:var(--tm-series-card-width,var(--tm-grid-card-min,108px));gap:9px;overflow-x:auto;overflow-y:hidden;padding:9px 0 2px;scrollbar-width:none;-webkit-overflow-scrolling:touch;overscroll-behavior-x:contain;touch-action:pan-x pan-y;cursor:grab;}',
            '.tm-series-track::-webkit-scrollbar{display:none;}',
            '.tm-series-track.is-dragging{cursor:grabbing;user-select:none;}',
            '.tm-series-track>.tm-card{min-width:0;scroll-snap-align:start;}',
            '.tm-series-block.is-expanded{overflow:visible;}',
            '.tm-series-block.is-expanded .tm-series-track{grid-auto-flow:row;grid-auto-columns:initial;grid-template-columns:repeat(auto-fill,minmax(var(--tm-grid-card-min,108px),1fr));overflow:visible;padding-bottom:0;cursor:default;}',
            '.tm-loading{display:flex;flex-direction:column;align-items:center;gap:12px;padding:60px 20px;opacity:.5;}',
            '.tm-loading i{font-size:2em;animation:tm-spin 1s linear infinite;}',
            '.tm-card{border-radius:var(--tm-card-radius,10px);overflow:hidden;position:relative;z-index:0;isolation:isolate;cursor:pointer;transition:all .18s;border:var(--tm-card-border-style,2px solid var(--tm-card-border,transparent));background:var(--tm-card-bg,rgba(127,127,127,.06));box-shadow:var(--tm-card-shadow,none);backdrop-filter:var(--tm-card-blur,none);display:flex;flex-direction:column;}',
            '.tm-card:hover{transform:translateY(-2px);box-shadow:var(--tm-card-hover-shadow,0 6px 20px var(--tm-shadow,rgba(0,0,0,.25)));}',
            '.tm-card.on{border-color:var(--SmartThemeQuoteColor,#7c6daf);box-shadow:0 0 0 1px var(--SmartThemeQuoteColor,#7c6daf),0 4px 16px rgba(0,0,0,.2);}',
            '.tm-card-img{width:100%;aspect-ratio:4/3;position:relative;background:var(--tm-control-bg,rgba(127,127,127,.1));display:flex;align-items:center;justify-content:center;overflow:hidden;flex-shrink:0;}',
            '.tm-card-img::after{content:"";position:absolute;inset:0;z-index:2;pointer-events:none;background-image:var(--tm-theme-card-frame-image,none);background-size:var(--tm-theme-card-frame-size,contain);background-position:var(--tm-theme-card-frame-position,center);background-repeat:var(--tm-theme-card-frame-repeat,no-repeat);mix-blend-mode:var(--tm-theme-card-frame-blend,normal);filter:var(--tm-theme-card-frame-filter,none);opacity:0;transition:opacity .2s;}',
            '.tm-card-preview-slot{position:absolute;inset:0;overflow:hidden;z-index:0;pointer-events:none;}',
            '.tm-card-preview-slot>img{position:absolute !important;inset:0 !important;width:100% !important;height:100% !important;min-width:0 !important;min-height:0 !important;max-width:none !important;max-height:none !important;margin:0 !important;padding:0 !important;display:block !important;box-sizing:border-box !important;object-fit:cover !important;object-position:var(--tm-image-focus-x,50%) var(--tm-image-focus-y,50%) !important;transform:scale(var(--tm-image-zoom,1)) !important;transform-origin:var(--tm-image-focus-x,50%) var(--tm-image-focus-y,50%) !important;opacity:0 !important;transition:opacity .16s ease !important;}',
            '.tm-card-preview-slot>img.tm-image-loaded{opacity:1 !important;}',
            '.tm-card.no-img .tm-card-img::before{content:"";position:absolute;inset:0;pointer-events:none;background-image:var(--tm-theme-surface-image,none);background-size:var(--tm-theme-surface-size,cover);background-position:var(--tm-theme-surface-position,center);background-repeat:var(--tm-theme-surface-repeat,no-repeat);opacity:var(--tm-theme-card-motif-opacity,0);filter:saturate(.9);}',
            '@media (hover:hover){.tm-card-menu{opacity:0;} .tm-card:hover .tm-card-menu{opacity:1;}}',
            '@media (hover:none){.tm-card-menu{opacity:.92 !important;}}',
            '.tm-card-info{padding:5px 7px 6px;background:var(--tm-card-bg,rgba(127,127,127,.06));min-height:36px;box-sizing:border-box;}',
            '.tm-card-name{font-size:.8em;font-weight:600;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--tm-text,#eee);}',
            '.tm-card-tag{font-size:.68em;line-height:1.2;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--tm-text,#aaa);opacity:.5;}',
            '.tm-card-noimg{position:relative;z-index:1;display:flex;flex-direction:column;align-items:center;gap:6px;opacity:.3;font-size:.75em;width:100%;height:100%;justify-content:center;}',
            '.tm-card-noimg i{font-size:2em;}',
            '.tm-follow .tm-card.no-img .tm-card-noimg>i,.tm-follow .tm-card.no-img .tm-card-noimg>span{display:none !important;}',
            '.tm-card.no-img{background:var(--tm-card-bg,rgba(127,127,127,.08));}',
            '.tm-badge-on{position:absolute;top:5px;right:5px;width:20px;height:20px;border-radius:50%;background:var(--SmartThemeQuoteColor,#7c6daf);color:var(--tm-accent-text,#fff);display:flex;align-items:center;justify-content:center;font-size:.6em;box-shadow:0 2px 6px var(--tm-shadow,rgba(0,0,0,.3));z-index:3;}',
            '.tm-badge-star{position:absolute;top:5px;left:5px;font-size:.85em;color:#f0b860;filter:drop-shadow(0 1px 3px rgba(0,0,0,.5));z-index:3;}',
            '.tm-badge-freq{position:absolute;bottom:5px;left:5px;padding:1px 6px;border-radius:8px;font-size:.6em;font-weight:600;background:rgba(0,0,0,.55);color:#fff;backdrop-filter:blur(4px);z-index:3;}',
            '.tm-card-menu{position:absolute;bottom:-3px;right:-1px;width:34px;height:32px;border:none;border-radius:var(--tm-control-radius,8px);background:transparent;color:var(--SmartThemeQuoteColor,#7c6daf);cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:1.05em;font-weight:900;line-height:1;overflow:hidden;opacity:0;transition:opacity .18s,transform .18s;z-index:3;pointer-events:auto;filter:drop-shadow(0 1px 2px rgba(0,0,0,.55));}',
            '.tm-card-menu:hover{background:transparent;opacity:1 !important;transform:scale(1.05);}',
            '.tm-card-check{position:absolute;top:5px;left:5px;width:22px;height:22px;border-radius:50%;border:2px solid rgba(255,255,255,.6);background:rgba(0,0,0,.3);backdrop-filter:blur(4px);display:flex;align-items:center;justify-content:center;font-size:.6em;color:transparent;cursor:pointer;transition:all .15s;z-index:3;}',
            '.tm-card-check.checked{background:var(--SmartThemeQuoteColor,#7c6daf);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;}',
            '.tm-card.batch-sel{border-color:var(--SmartThemeQuoteColor,#7c6daf);opacity:.85;}',
            '.tm-batch-area{flex-shrink:0;}',
            '.tm-batch-bar{display:flex;align-items:center;gap:6px;padding:8px 12px;background:var(--tm-head-bg,rgba(124,109,175,.06));border-bottom:1px solid var(--tm-border,rgba(124,109,175,.15));flex-wrap:nowrap;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none;}',
            '.tm-batch-bar::-webkit-scrollbar{display:none;}',
            '.tm-batch-info{font-size:.82em;font-weight:600;color:var(--SmartThemeQuoteColor,#7c6daf);white-space:nowrap;flex-shrink:0;}',
            '.tm-batch-divider{width:1px;height:16px;background:rgba(127,127,127,.25);flex-shrink:0;margin:0 2px;}',
            '.tm-batch-acts{display:flex;gap:5px;flex-shrink:0;flex-wrap:nowrap;}',
            '.tm-batch-btn{padding:5px 10px;border-radius:var(--tm-control-radius,6px);font-size:.78em;cursor:pointer;border:var(--tm-control-border-style,1px solid var(--tm-control-border,rgba(127,127,127,.2)));background:var(--tm-control-bg,rgba(127,127,127,.07));box-shadow:var(--tm-control-shadow,none);color:inherit;font-family:inherit;transition:.15s;white-space:nowrap;flex-shrink:0;}',
            '.tm-batch-btn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.1);}',
            '.tm-batch-btn:disabled{opacity:.4;cursor:wait;pointer-events:none;}',
            '.tm-batch-btn.danger{border-color:#e57373;color:#e57373;}',
            '.tm-batch-btn.danger:hover{background:#e57373;color:#fff;}',
            '.tm-batch-day-night:not(:disabled) i{color:#f0a64a;}',
            '.tm-batch-series:not(:disabled) i{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-empty{display:flex;flex-direction:column;align-items:center;gap:10px;padding:40px 20px;opacity:.35;font-size:.9em;text-align:center;}',
            '.tm-empty i{font-size:2.6em;}',
            '.tm-bottombar{position:relative;overflow:hidden;display:flex !important;align-items:center;gap:6px;padding:10px 14px;padding-bottom:max(10px, env(safe-area-inset-bottom, 10px));flex-shrink:0;border-top:1px solid var(--tm-border,rgba(127,127,127,.1));background:var(--tm-head-bg,rgba(0,0,0,.12));backdrop-filter:blur(14px);}',
            '.tm-bottom-status{flex:1;min-width:0;display:flex;align-items:center;gap:7px;cursor:pointer;border-radius:var(--tm-control-radius,8px);padding:5px 7px;transition:.15s;border:1px solid transparent;}',
            '.tm-bottom-status:hover{background:rgba(127,127,127,.08);border-color:rgba(127,127,127,.12);}',
            '.tm-status-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0;}',
            '.tm-status-dot.gray{background:rgba(127,127,127,.5);}',
            '.tm-status-dot.green{background:#4caf50;}',
            '.tm-status-text{font-size:.82em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;opacity:.9;}',
            '.tm-bottom-btn{width:36px;height:36px;border-radius:var(--tm-control-radius,50%);border:var(--tm-control-border-style,1px solid var(--tm-control-border,rgba(127,127,127,.15)));background:var(--tm-control-bg,rgba(127,127,127,.06));box-shadow:var(--tm-control-shadow,none);color:inherit;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:.9em;transition:.18s;flex-shrink:0;}',
            '.tm-bottom-btn:hover{background:rgba(127,127,127,.15);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-bottom-btn.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:var(--tm-accent-text,#fff);border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
'.tm-sheet-overlay{position:absolute !important;inset:0 !important;z-index:1 !important;background:rgba(0,0,0,.45) !important;pointer-events:auto !important;}',
            '.tm-sheet{position:absolute;bottom:0;left:0;right:0;max-height:88vh;max-height:88dvh;background:var(--tm-bg2,var(--SmartThemeBackgroundColor,#1a1a1e));color:var(--tm-text,var(--SmartThemeBodyColor,#eee));border-radius:var(--tm-panel-radius,18px) var(--tm-panel-radius,18px) 0 0;overflow-y:auto;animation:tm-sheet-up .25s ease;border:1px solid var(--tm-control-border,rgba(127,127,127,.15));border-bottom:none;box-shadow:var(--tm-panel-shadow,0 -12px 36px var(--tm-shadow,rgba(0,0,0,.28)));backdrop-filter:var(--tm-panel-blur,none);}',
            '.tm-sheet-handle{width:36px;height:4px;border-radius:2px;background:rgba(127,127,127,.25);margin:10px auto 4px;}',
            '.tm-sheet-content{padding:4px 20px 32px;}',
            '.tm-sheet-title{font-weight:700;font-size:1.05em;padding:10px 0 14px;display:flex;align-items:center;gap:8px;}',
            '.tm-sheet-title i{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-edit-sheet-title{justify-content:space-between;gap:12px;}',
            '.tm-edit-sheet-title>span{display:flex;align-items:center;gap:7px;min-width:0;}',
            '.tm-edit-sheet-title b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-day-night-toggle{display:flex;align-items:center;padding:2px;border-radius:11px;background:rgba(127,127,127,.1);border:1px solid rgba(127,127,127,.14);flex-shrink:0;}',
            '.tm-day-night-toggle button{width:32px;height:28px;border:0;border-radius:8px;background:transparent;color:inherit;opacity:.42;cursor:pointer;display:flex;align-items:center;justify-content:center;}',
            '.tm-day-night-toggle button i{color:inherit;}',
            '.tm-day-night-toggle button[data-variant=day].on{background:rgba(244,178,72,.2);color:#e99c25;opacity:1;}',
            '.tm-day-night-toggle button[data-variant=night].on{background:rgba(113,121,205,.22);color:#8e98e6;opacity:1;}',
            '.tm-day-night-hint{margin:-4px 0 12px;}',
            '.tm-day-night-assign{display:grid;grid-template-columns:minmax(0,1fr) 34px minmax(0,1fr);gap:8px;align-items:stretch;margin:4px 0 12px;}',
            '.tm-day-night-choice{display:flex;min-width:0;flex-direction:column;gap:6px;padding:10px;border-radius:10px;border:1px solid rgba(127,127,127,.16);background:rgba(127,127,127,.06);}',
            '.tm-day-night-choice-label{display:flex;align-items:center;gap:6px;font-size:.8em;font-weight:650;}',
            '.tm-day-night-choice.is-day .tm-day-night-choice-label i{color:#e99c25;}',
            '.tm-day-night-choice.is-night .tm-day-night-choice-label i{color:#8e98e6;}',
            '.tm-day-night-choice select{width:100%;min-width:0;background:var(--tm-control-bg,rgba(127,127,127,.08));border:1px solid rgba(127,127,127,.2);border-radius:7px;color:inherit;padding:7px 8px;font-family:inherit;}',
            '.tm-day-night-swap{width:34px;height:34px;box-sizing:border-box;align-self:center;display:grid;place-items:center;padding:0;line-height:1;border-radius:50%;border:1px solid rgba(127,127,127,.2);background:rgba(127,127,127,.08);color:inherit;cursor:pointer;}',
            '.tm-day-night-swap:hover{color:var(--SmartThemeQuoteColor,#7c6daf);border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-day-night-swap-icon{display:block;width:18px;height:18px;overflow:visible;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;}',
            '.tm-day-night-members{display:flex;flex-direction:column;gap:7px;margin:12px 0;}',
            '.tm-day-night-members span{display:flex;align-items:center;gap:8px;padding:9px 11px;border-radius:8px;background:rgba(127,127,127,.07);font-size:.8em;overflow-wrap:anywhere;}',
            '.tm-day-night-members span:first-child i{color:#e99c25;}',
            '.tm-day-night-members span:last-child i{color:#8e98e6;}',
            '.tm-day-night-delete-actions{flex-wrap:wrap;}',
            '.tm-series-hint{margin:-4px 0 10px;}',
            '.tm-series-selected-list{display:flex;gap:6px;overflow-x:auto;padding:2px 0 11px;margin-bottom:3px;scrollbar-width:none;}',
            '.tm-series-selected-list::-webkit-scrollbar{display:none;}',
            '.tm-series-selected-list span{display:flex;align-items:center;gap:6px;max-width:220px;padding:6px 9px;border-radius:10px;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.12);font-size:.74em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;flex-shrink:0;}',
            '.tm-series-selected-list i{color:var(--SmartThemeQuoteColor,#7c6daf);opacity:.75;}',
            '.tm-series-member-list{display:flex;flex-direction:column;gap:6px;margin:9px 0 2px;}',
            '.tm-series-member-row{display:flex;align-items:center;gap:9px;min-height:42px;padding:6px 7px 6px 10px;border-radius:9px;background:rgba(127,127,127,.06);border:1px solid rgba(127,127,127,.1);}',
            '.tm-series-member-row>i{width:18px;text-align:center;color:var(--SmartThemeQuoteColor,#7c6daf);opacity:.75;flex-shrink:0;}',
            '.tm-series-member-row>div{display:flex;min-width:0;flex:1;flex-direction:column;gap:2px;}',
            '.tm-series-member-row strong{font-size:.8em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-series-member-row small{font-size:.66em;color:#e6a05b;}',
            '.tm-series-member-remove{width:32px;height:32px;display:grid;place-items:center;border:0;color:inherit;flex-shrink:0;}',
            '.tm-series-member-remove:hover{color:#e57373;}',
            '.tm-series-manage-actions{align-items:center;flex-wrap:wrap;}',
            '.tm-series-manage-actions>span{flex:1;}',
            '.tm-ctx-item{display:flex;align-items:center;gap:12px;padding:14px 4px;cursor:pointer;border-bottom:1px solid rgba(127,127,127,.08);transition:.15s;border-radius:0;}',
            '.tm-ctx-item:last-child{border-bottom:none;}',
            '.tm-ctx-item:hover{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-ctx-item i{width:20px;text-align:center;opacity:.75;font-size:1em;}',
            '.tm-ctx-item.danger{color:#e57373;}',
            '.tm-ctx-item.danger:hover{color:#ef5350;}',
            '.tm-ctx-theme-name{font-size:.85em;opacity:.5;padding:2px 0 10px;border-bottom:1px solid rgba(127,127,127,.1);margin-bottom:4px;}',
            '.tm-sec-title{font-size:.75em;font-weight:700;opacity:.55;text-transform:uppercase;letter-spacing:.07em;padding:10px 0 7px;}',
            '.tm-divider{height:1px;background:rgba(127,127,127,.12);margin:6px 0 12px;}',
            '.tm-hint{font-size:.76em;opacity:.5;line-height:1.4;}',
            '.tm-btn-row{display:flex;gap:8px;flex-wrap:wrap;}',
            '.tm-data-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:8px;}',
            '.tm-data-grid .tm-btn{display:flex;align-items:center;justify-content:center;gap:5px;min-width:0;padding:8px 5px;font-size:.78em;line-height:1.2;white-space:nowrap;}',
            '.tm-btn{padding:8px 16px;border-radius:var(--tm-control-radius,8px);border:none;box-shadow:var(--tm-control-shadow,none);cursor:pointer;font-size:.87em;font-weight:600;transition:.18s;font-family:inherit;}',
            '.tm-btn:disabled{opacity:.45;cursor:default;filter:none;pointer-events:none;}',
            '.tm-btn-safe{background:var(--SmartThemeQuoteColor,#7c6daf);color:var(--tm-accent-text,#fff);}',
            '.tm-btn-safe:hover{filter:brightness(1.1);}',
            '.tm-btn-outline{background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.22);color:inherit;}',
            '.tm-btn-outline:hover{background:rgba(127,127,127,.15);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-btn-danger{background:rgba(229,115,115,.1);border:1px solid #e57373;color:#e57373;}',
            '.tm-btn-danger:hover{background:#e57373;color:#fff;}',
            '.tm-binding-hint{margin:-4px 0 12px;}',
            '.tm-binding-card{padding:12px;border-radius:var(--tm-panel-radius,12px);border:1px solid var(--tm-control-border,rgba(127,127,127,.16));background:var(--tm-control-bg,rgba(127,127,127,.06));margin-bottom:10px;}',
            '.tm-binding-card.is-active{border-color:color-mix(in srgb,var(--SmartThemeQuoteColor,#7c6daf) 55%,transparent);box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--SmartThemeQuoteColor,#7c6daf) 16%,transparent);}',
            '.tm-binding-head{display:flex;align-items:flex-start;gap:9px;}',
            '.tm-binding-head>i{width:20px;padding-top:2px;text-align:center;color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-binding-head>div{display:flex;flex:1;min-width:0;flex-direction:column;gap:2px;}',
            '.tm-binding-head strong{font-size:.88em;}',
            '.tm-binding-head small{font-size:.72em;opacity:.5;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-binding-head>span{font-size:.66em;padding:2px 6px;border-radius:8px;background:var(--SmartThemeQuoteColor,#7c6daf);color:var(--tm-accent-text,#fff);white-space:nowrap;}',
            '.tm-binding-status{font-size:.76em;opacity:.65;margin:10px 0 8px;padding-left:29px;}',
            '.tm-binding-actions{display:flex;justify-content:flex-end;gap:7px;flex-wrap:wrap;}',
            '.tm-binding-actions .tm-btn{font-size:.78em;padding:7px 11px;}',
            '.tm-field{display:flex;flex-direction:column;gap:5px;margin-bottom:10px;}',
            '.tm-field label{font-size:.8em;opacity:.7;font-weight:500;}',
            '.tm-field input[type=text],.tm-field select,.tm-field textarea{background:var(--tm-control-bg,rgba(127,127,127,.08));border:var(--tm-control-border-style,1px solid var(--tm-control-border,rgba(127,127,127,.2)));border-radius:var(--tm-control-radius,8px);color:inherit;padding:9px 11px;font-size:.9em;width:100%;box-sizing:border-box;font-family:inherit;}',
            '.tm-setting-copy{display:flex;flex-direction:column;gap:2px;min-width:0;}',
            '.tm-setting-copy small{font-size:.72em;opacity:.5;line-height:1.3;font-weight:400;}',
            '.tm-field textarea{resize:none;}',
            '.tm-field input:focus,.tm-field select:focus,.tm-field textarea:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-fab-custom-row{display:flex;align-items:center;gap:10px;}',
            '.tm-fab-preview{width:48px;height:48px;overflow:hidden;display:flex;align-items:center;justify-content:center;flex-shrink:0;}',
            '.tm-fab-preview img{width:100%;height:100%;object-fit:contain;}',
            '.tm-fab-default-preview{width:100%;height:100%;border-radius:50%;background:var(--SmartThemeQuoteColor,#7c6daf);display:flex;align-items:center;justify-content:center;color:var(--tm-accent-text,#fff);}',
            '.tm-fab-custom-actions{display:flex;gap:6px;flex:1;flex-wrap:wrap;}',
            '.tm-fab-custom-actions .tm-btn{font-size:.8em;flex:1 1 120px;}',
            '.tm-range{width:100%;accent-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-import-cat-list{display:flex;flex-direction:column;gap:7px;margin:8px 0 12px;max-height:42vh;overflow:auto;}',
            '.tm-import-cat-item{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:8px;background:rgba(127,127,127,.06);border:1px solid rgba(127,127,127,.1);}',
            '.tm-import-cat-item span{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:.88em;}',
            '.tm-import-cat-item small{opacity:.45;font-size:.75em;white-space:nowrap;}',
            '.tm-import-cat-tools{display:flex;gap:8px;justify-content:flex-end;margin-bottom:8px;}',
            '.tm-cat-export-item{display:flex;align-items:center;gap:9px;width:100%;padding:9px 10px;border-radius:8px;background:rgba(127,127,127,.06);border:1px solid rgba(127,127,127,.1);color:inherit;font-family:inherit;text-align:left;cursor:pointer;}',
            '.tm-cat-export-item:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.1);}',
            '.tm-cat-export-item span{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:.88em;}',
            '.tm-cat-export-item small{opacity:.45;font-size:.75em;white-space:nowrap;}',
            '.tm-frow{display:flex;gap:7px;align-items:stretch;}',
            '.tm-frow select{flex:1;}',
            '.tm-bg-bind-card{width:100%;display:grid;grid-template-columns:72px minmax(0,1fr) 18px;gap:10px;align-items:center;padding:8px;border-radius:8px;border:1px solid rgba(127,127,127,.2);background:rgba(127,127,127,.08);color:inherit;text-align:left;font-family:inherit;cursor:pointer;}',
            '.tm-bg-bind-card:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.12);}',
            '.tm-bg-bind-thumb{height:48px;border-radius:7px;background-size:cover;background-position:center;background-color:rgba(127,127,127,.14);border:1px solid rgba(127,127,127,.14);display:flex;align-items:center;justify-content:center;overflow:hidden;}',
            '.tm-bg-bind-thumb.empty{background:repeating-linear-gradient(45deg,rgba(127,127,127,.08),rgba(127,127,127,.08) 8px,rgba(127,127,127,.16) 8px,rgba(127,127,127,.16) 16px);}',
            '.tm-bg-bind-thumb i{opacity:.4;font-size:1.2em;}',
            '.tm-bg-bind-info{min-width:0;}',
            '.tm-bg-bind-name{font-size:.88em;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-bg-bind-sub{font-size:.72em;opacity:.48;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-bg-bind-card>i{opacity:.35;}',
            '.tm-theme-bind-card{width:100%;box-sizing:border-box;display:grid;grid-template-columns:38px minmax(0,1fr) 16px;gap:10px;align-items:center;padding:9px 11px;border-radius:8px;border:1px solid rgba(127,127,127,.2);background:rgba(127,127,127,.08);color:inherit;text-align:left;font-family:inherit;cursor:pointer;}',
            '.tm-theme-bind-card:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.12);}',
            '.tm-theme-bind-icon{width:38px;height:38px;border-radius:9px;display:grid;place-items:center;background:rgba(127,127,127,.11);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-theme-bind-copy{display:flex;min-width:0;flex-direction:column;gap:3px;}',
            '.tm-theme-bind-copy strong{font-size:.86em;font-weight:650;}',
            '.tm-theme-bind-copy small{font-size:.73em;opacity:.5;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-theme-bind-chevron{font-size:.8em;opacity:.34;}',
            '.tm-bindings-all-hint{margin:-4px 0 12px;}',
            '.tm-bindings-all-section{margin:0 0 12px;}',
            '.tm-bindings-all-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0 2px 7px;font-size:.78em;font-weight:650;opacity:.65;}',
            '.tm-bindings-all-head span{display:flex;align-items:center;gap:6px;}',
            '.tm-bindings-all-head small{font-size:.9em;font-weight:500;}',
            '.tm-bindings-all-list{display:flex;flex-direction:column;border:1px solid rgba(127,127,127,.16);border-radius:10px;overflow:hidden;background:rgba(127,127,127,.04);}',
            '.tm-bindings-all-row{display:grid;grid-template-columns:34px minmax(0,1fr) auto;gap:9px;align-items:center;padding:9px 10px;border-bottom:1px solid rgba(127,127,127,.12);}',
            '.tm-bindings-all-row:last-child{border-bottom:0;}',
            '.tm-bindings-all-icon{width:34px;height:34px;border-radius:8px;display:grid;place-items:center;background:rgba(127,127,127,.1);color:var(--SmartThemeQuoteColor,#7c6daf);font-size:.82em;}',
            '.tm-bindings-all-copy{display:flex;min-width:0;flex-direction:column;gap:2px;}',
            '.tm-bindings-all-copy strong{font-size:.8em;font-weight:600;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-bindings-all-copy small{font-size:.69em;opacity:.45;}',
            '.tm-bindings-all-remove{padding:6px 9px;border:1px solid rgba(229,115,115,.35);border-radius:7px;background:rgba(229,115,115,.08);color:#df7777;font:inherit;font-size:.72em;cursor:pointer;white-space:nowrap;}',
            '.tm-bindings-all-remove:hover{background:rgba(229,115,115,.16);border-color:rgba(229,115,115,.55);}',
            '.tm-bindings-all-empty{display:flex;min-height:128px;flex-direction:column;align-items:center;justify-content:center;gap:6px;margin:4px 0 10px;border:1px dashed rgba(127,127,127,.2);border-radius:10px;color:inherit;}',
            '.tm-bindings-all-empty>i{font-size:1.35em;color:var(--SmartThemeQuoteColor,#7c6daf);opacity:.55;}',
            '.tm-bindings-all-empty>strong{font-size:.86em;}',
            '.tm-bindings-all-empty>span{font-size:.73em;opacity:.48;text-align:center;}',
            '.tm-bindings-all-foot{padding-top:12px;border-top:1px solid rgba(127,127,127,.1);}',
            '.tm-bg-picker-tools{display:grid;grid-template-columns:minmax(0,1fr) 34px 34px;gap:7px;align-items:center;margin-bottom:10px;}',
            '.tm-bg-search-wrap{display:flex;align-items:center;gap:7px;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.18);border-radius:8px;padding:0 9px;min-width:0;}',
            '.tm-bg-search-wrap i{opacity:.45;font-size:.85em;}',
            '.tm-bg-search-wrap input{flex:1;min-width:0;background:transparent;border:none;color:inherit;padding:8px 0;font-family:inherit;font-size:.86em;outline:none;}',
            '.tm-bg-picker-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(var(--tm-bg-card-min,132px),1fr));gap:10px;padding-bottom:8px;}',
            '.tm-bg-picker-card{position:relative;display:flex;flex-direction:column;gap:6px;padding:7px;border-radius:8px;border:2px solid transparent;background:rgba(127,127,127,.06);color:inherit;font-family:inherit;text-align:left;cursor:pointer;min-width:0;}',
            '.tm-bg-picker-card:hover{background:rgba(127,127,127,.11);}',
            '.tm-bg-picker-card.on{border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-bg-picker-thumb{width:100%;aspect-ratio:4/3;border-radius:6px;background-size:cover;background-position:center;background-color:rgba(127,127,127,.12);border:1px solid rgba(127,127,127,.12);display:flex;align-items:center;justify-content:center;overflow:hidden;}',
            '.tm-bg-picker-thumb.empty{background:repeating-linear-gradient(45deg,rgba(127,127,127,.08),rgba(127,127,127,.08) 8px,rgba(127,127,127,.16) 8px,rgba(127,127,127,.16) 16px);}',
            '.tm-bg-picker-thumb i{opacity:.38;font-size:1.6em;}',
            '.tm-bg-picker-name{font-size:.75em;font-weight:600;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-bg-picker-card>i{position:absolute;top:9px;right:9px;color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(0,0,0,.35);border-radius:50%;opacity:0;}',
            '.tm-bg-picker-card.on>i{opacity:1;}',
            '.tm-bg-rename{position:absolute;right:8px;bottom:28px;width:26px;height:26px;border:none;border-radius:50%;background:rgba(0,0,0,.48);color:#fff;display:flex;align-items:center;justify-content:center;cursor:pointer;opacity:.72;z-index:1;}',
            '.tm-bg-rename:hover{opacity:1;background:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-imgarea{width:100%;height:160px;background:rgba(127,127,127,.06);border:2px dashed rgba(127,127,127,.25);border-radius:10px;display:flex;align-items:center;justify-content:center;cursor:pointer;overflow:hidden;transition:border-color .18s;}',
            '.tm-imgarea:hover,.tm-imgarea.drag{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.1);}',
            '.tm-imgph{display:flex;flex-direction:column;align-items:center;gap:6px;opacity:.4;font-size:.82em;pointer-events:none;}',
            '.tm-imgph i{font-size:1.8em;}',
            '.tm-imgarea img{width:100%;height:100%;object-fit:contain;}',
            '.tm-img-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:7px;}',
            '.tm-crop-hint{margin:-4px 0 10px;}',
            '.tm-crop-stage{width:100%;aspect-ratio:4/3;background:#111;border-radius:10px;overflow:hidden;border:1px solid rgba(127,127,127,.18);}',
            '.tm-crop-stage canvas{width:100%;height:100%;display:block;}',
            '.tm-crop-controls{display:grid;gap:8px;margin:10px 0 12px;}',
            '.tm-crop-controls label{display:grid;grid-template-columns:42px minmax(0,1fr);gap:8px;align-items:center;font-size:.78em;opacity:.78;}',
            '.tm-crop-controls input{width:100%;accent-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-edit-foot{display:flex;gap:9px;justify-content:flex-end;padding-top:14px;border-top:1px solid rgba(127,127,127,.1);margin-top:10px;}',
            '.tm-tags-wrap{display:flex;flex-wrap:wrap;gap:5px;margin-top:4px;}',
            '.tm-tag-chip{display:inline-flex;align-items:center;gap:4px;padding:3px 8px 3px 10px;border-radius:12px;background:var(--SmartThemeQuoteColor,#7c6daf);color:var(--tm-accent-text,#fff);font-size:.78em;font-weight:500;}',
            '.tm-tag-chip-x{background:none;border:none;color:#fff;cursor:pointer;font-size:.85em;line-height:1;padding:0 2px;opacity:.7;}',
            '.tm-tag-chip-x:hover{opacity:1;}',
            '.tm-tag-add-row{display:flex;gap:6px;margin-top:6px;}',
            '.tm-tag-add-row input{flex:1;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;padding:6px 10px;font-size:.82em;font-family:inherit;box-sizing:border-box;}',
            '.tm-tag-add-row input:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-cat-item{display:flex;align-items:center;gap:8px;padding:9px 12px;background:rgba(127,127,127,.06);border-radius:9px;border:1px solid rgba(127,127,127,.1);transition:none;margin-bottom:7px;}',
            '.tm-cat-item:hover{background:rgba(127,127,127,.11);}',
            '.tm-cat-item.drag-over-top{border-top:2px solid var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-cat-item.drag-over-bottom{border-bottom:2px solid var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-cat-item.dragging{opacity:.3;}',
            '@media (max-width:430px){.tm-head{gap:5px;padding-left:8px;padding-right:8px}.tm-head-title-switcher{height:40px;gap:5px;padding-right:5px}.tm-head-name{font-size:.9em}.tm-head-actions{gap:0}.tm-icon-btn{width:32px}.tm-app-page-avatars,.tm-app-page-backgrounds{padding:14px}}',
            '@media (max-width:480px){.tm-day-night-assign{grid-template-columns:minmax(0,1fr) 30px minmax(0,1fr);gap:5px}.tm-day-night-choice{padding:8px 7px}.tm-day-night-choice-label{font-size:.74em}.tm-day-night-choice select{font-size:.76em;padding:6px 5px}.tm-day-night-swap{width:30px;height:30px}.tm-day-night-swap-icon{width:16px;height:16px}.tm-edit-sheet-title{align-items:flex-start}.tm-day-night-delete-actions .tm-btn{flex:1;min-width:96px;padding-left:8px;padding-right:8px}}',
            '.tm-drag-handle{opacity:.35;cursor:grab;padding:0 6px;font-size:.9em;touch-action:none;}',
            '.tm-cat-name{flex:1;font-size:.88em;}',
            '.tm-cat-count{font-size:.74em;opacity:.45;}',
            '.tm-cat-add-row{display:flex;gap:8px;}',
            '.tm-cat-add-row input{flex:1;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;padding:8px 11px;font-size:.88em;font-family:inherit;box-sizing:border-box;}',
            '.tm-cat-add-row input:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-btn-sm{padding:5px 7px;border-radius:6px;cursor:pointer;font-size:.78em;background:rgba(127,127,127,.07);border:1px solid rgba(127,127,127,.14);transition:all .15s;color:inherit;font-family:inherit;}',
            '.tm-btn-sm:hover{background:rgba(127,127,127,.15);}',
            '.tm-row-inline{display:flex;align-items:center;justify-content:space-between;margin-bottom:6px;}',
            '.tm-row-inline label{opacity:.8;font-size:.88em;}',
            '.tm-follow-detail{margin-left:14px;padding-left:10px;border-left:2px solid color-mix(in srgb,var(--SmartThemeQuoteColor,#7c6daf) 24%,transparent);}',
            '.tm-follow-detail.is-disabled{opacity:.38;}',
            '.tm-chk{width:17px;height:17px;accent-color:var(--SmartThemeQuoteColor,#7c6daf);cursor:pointer;}',
            '.tm-storage-info{font-size:.72em;opacity:.45;padding:4px 0;}',
            '.tm-overlay.tm-follow,.tm-overlay.tm-follow button,.tm-overlay.tm-follow input,.tm-overlay.tm-follow select,.tm-overlay.tm-follow textarea{font-family:var(--tm-theme-font,inherit) !important;}',
            '.tm-overlay.tm-follow i.fa-solid,.tm-overlay.tm-follow i.fa-regular{font-family:"Font Awesome 6 Free" !important;}',
            '.tm-overlay.tm-follow i.fa-brands{font-family:"Font Awesome 6 Brands" !important;}',
            '.tm-overlay.tm-follow.tm-has-manager-background::after{background-image:var(--tm-theme-manager-image,none) !important;background-size:var(--tm-theme-manager-size,cover) !important;background-position:var(--tm-theme-manager-position,center) !important;background-repeat:var(--tm-theme-manager-repeat,no-repeat) !important;opacity:var(--tm-theme-manager-opacity,.96) !important;}',
            '.tm-follow.tm-has-topbar-decoration .tm-head::before{background-image:var(--tm-theme-topbar-image,none) !important;background-size:var(--tm-theme-topbar-size,cover) !important;background-position:var(--tm-theme-topbar-position,center) !important;background-repeat:var(--tm-theme-topbar-repeat,no-repeat) !important;opacity:1 !important;}',
            '.tm-follow.tm-topbar-overhang .tm-head{overflow:visible !important;z-index:6;isolation:isolate;}',
            '.tm-follow.tm-topbar-overhang .tm-head::before{inset:auto 0 auto 0 !important;top:var(--tm-theme-topbar-overlay-top,0) !important;width:100% !important;height:var(--tm-theme-topbar-overlay-height,100%) !important;pointer-events:none !important;}',
            '.tm-follow.tm-has-bottombar-decoration .tm-bottombar::before{background-image:var(--tm-theme-bottombar-image,none) !important;background-size:var(--tm-theme-bottombar-size,cover) !important;background-position:var(--tm-theme-bottombar-position,center) !important;background-repeat:var(--tm-theme-bottombar-repeat,no-repeat) !important;opacity:1 !important;}',
            '.tm-follow.tm-has-top-icon .tm-head-actions .tm-icon-btn>i{content:var(--tm-theme-top-icon-image,normal) !important;width:var(--tm-theme-top-icon-size,24px) !important;height:var(--tm-theme-top-icon-size,24px) !important;object-fit:contain !important;transform:var(--tm-theme-top-icon-transform,none) !important;}',
            '.tm-follow.tm-has-bottom-refresh-icon #tm-refresh{--tm-bottom-current-image:var(--tm-theme-bottom-refresh-image,none);--tm-bottom-current-transform:var(--tm-theme-bottom-refresh-transform,none);--tm-bottom-current-size:var(--tm-theme-bottom-refresh-size,24px);--tm-bottom-current-bg-size:var(--tm-theme-bottom-refresh-bg-size,contain);--tm-bottom-current-bg-position:var(--tm-theme-bottom-refresh-bg-position,center);--tm-bottom-current-bg-repeat:var(--tm-theme-bottom-refresh-bg-repeat,no-repeat);--tm-bottom-current-filter:var(--tm-theme-bottom-refresh-filter,none);--tm-bottom-current-opacity:var(--tm-theme-bottom-refresh-opacity,1);}',
            '.tm-follow.tm-has-bottom-batch-icon #tm-batch-toggle{--tm-bottom-current-image:var(--tm-theme-bottom-batch-image,none);--tm-bottom-current-transform:var(--tm-theme-bottom-batch-transform,none);--tm-bottom-current-size:var(--tm-theme-bottom-batch-size,24px);--tm-bottom-current-bg-size:var(--tm-theme-bottom-batch-bg-size,contain);--tm-bottom-current-bg-position:var(--tm-theme-bottom-batch-bg-position,center);--tm-bottom-current-bg-repeat:var(--tm-theme-bottom-batch-bg-repeat,no-repeat);--tm-bottom-current-filter:var(--tm-theme-bottom-batch-filter,none);--tm-bottom-current-opacity:var(--tm-theme-bottom-batch-opacity,1);}',
            '.tm-follow.tm-has-bottom-settings-icon #tm-bottom-settings{--tm-bottom-current-image:var(--tm-theme-bottom-settings-image,none);--tm-bottom-current-transform:var(--tm-theme-bottom-settings-transform,none);--tm-bottom-current-size:var(--tm-theme-bottom-settings-size,24px);--tm-bottom-current-bg-size:var(--tm-theme-bottom-settings-bg-size,contain);--tm-bottom-current-bg-position:var(--tm-theme-bottom-settings-bg-position,center);--tm-bottom-current-bg-repeat:var(--tm-theme-bottom-settings-bg-repeat,no-repeat);--tm-bottom-current-filter:var(--tm-theme-bottom-settings-filter,none);--tm-bottom-current-opacity:var(--tm-theme-bottom-settings-opacity,1);}',
            '.tm-follow.tm-has-bottom-refresh-icon #tm-refresh,.tm-follow.tm-has-bottom-batch-icon #tm-batch-toggle,.tm-follow.tm-has-bottom-settings-icon #tm-bottom-settings{padding:0 !important;}',
            '.tm-follow.tm-has-bottom-refresh-icon #tm-refresh>i,.tm-follow.tm-has-bottom-batch-icon #tm-batch-toggle>i,.tm-follow.tm-has-bottom-settings-icon #tm-bottom-settings>i{content:"" !important;display:block !important;flex-shrink:0 !important;width:var(--tm-bottom-current-size,24px) !important;height:var(--tm-bottom-current-size,24px) !important;background-image:var(--tm-bottom-current-image,none) !important;background-size:var(--tm-bottom-current-bg-size,contain) !important;background-position:var(--tm-bottom-current-bg-position,center) !important;background-repeat:var(--tm-bottom-current-bg-repeat,no-repeat) !important;transform:var(--tm-bottom-current-transform,none) !important;filter:var(--tm-bottom-current-filter,none) !important;opacity:var(--tm-bottom-current-opacity,1) !important;color:transparent !important;font-size:0 !important;}',
            '.tm-follow:not(.tm-follow-grid).tm-light .tm-grid-area{--tm-card-bg:rgba(0,0,0,.04);--tm-card-border:transparent;--tm-control-bg:rgba(0,0,0,.06);--tm-text:#111;--tm-theme-card-motif-opacity:0;--tm-card-radius:10px;--tm-card-border-style:2px solid transparent;--tm-card-shadow:none;--tm-card-hover-shadow:0 6px 20px rgba(0,0,0,.25);--tm-card-blur:none;}',
            '.tm-follow:not(.tm-follow-grid).tm-dark .tm-grid-area{--tm-card-bg:rgba(255,255,255,.05);--tm-card-border:transparent;--tm-control-bg:rgba(255,255,255,.06);--tm-text:#eee;--tm-theme-card-motif-opacity:0;--tm-card-radius:10px;--tm-card-border-style:2px solid transparent;--tm-card-shadow:none;--tm-card-hover-shadow:0 6px 20px rgba(0,0,0,.35);--tm-card-blur:none;}',
            '.tm-follow.tm-follow-grid .tm-card{border:0 solid transparent !important;border-radius:0 !important;overflow:visible !important;background:transparent !important;box-shadow:none !important;backdrop-filter:none !important;}',
            '.tm-follow.tm-follow-grid .tm-card:hover{box-shadow:none !important;}',
            '.tm-follow.tm-follow-preview-shape .tm-card-img,.tm-follow.tm-follow-card-frame .tm-card-img{aspect-ratio:var(--tm-preview-aspect,4 / 3) !important;border-radius:var(--tm-preview-radius,0) !important;border:var(--tm-preview-border-style,1px solid transparent) !important;box-shadow:var(--tm-preview-shadow,none) !important;clip-path:var(--tm-preview-clip-path,none) !important;-webkit-mask-image:var(--tm-preview-mask-image,none) !important;mask-image:var(--tm-preview-mask-image,none) !important;-webkit-mask-size:var(--tm-preview-mask-size,cover) !important;mask-size:var(--tm-preview-mask-size,cover) !important;-webkit-mask-position:var(--tm-preview-mask-position,center) !important;mask-position:var(--tm-preview-mask-position,center) !important;-webkit-mask-repeat:var(--tm-preview-mask-repeat,no-repeat) !important;mask-repeat:var(--tm-preview-mask-repeat,no-repeat) !important;}',
            '.tm-follow.tm-follow-grid .tm-card-info{border-radius:var(--tm-card-radius,0) !important;background:var(--tm-card-bg,rgba(127,127,127,.08)) !important;}',
            '.tm-follow.tm-compact-card-info .tm-card-info{background:transparent !important;border-radius:0 !important;text-align:center !important;padding:6px 2px !important;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;}',
            '.tm-follow.tm-compact-card-info .tm-card-name,.tm-follow.tm-compact-card-info .tm-card-tag{width:100%;text-align:center;}',
            '.tm-follow.tm-follow-grid .tm-card.on .tm-card-img,.tm-follow.tm-follow-grid .tm-card.batch-sel .tm-card-img{outline:2px solid var(--SmartThemeQuoteColor,#7c6daf) !important;outline-offset:1px;}',
            '.tm-follow.tm-follow-card-frame .tm-card-img{background:transparent !important;}',
            '.tm-follow.tm-follow-card-frame.tm-card-frame-blended .tm-card-img{background:var(--tm-card-bg,rgba(127,127,127,.08)) !important;}',
            '.tm-follow.tm-follow-card-frame .tm-card-img>.tm-card-preview-slot,.tm-follow.tm-follow-card-frame .tm-card-noimg{position:absolute !important;left:var(--tm-preview-slot-left,0%) !important;top:var(--tm-preview-slot-top,0%) !important;right:auto !important;bottom:auto !important;width:var(--tm-preview-slot-width,100%) !important;height:var(--tm-preview-slot-height,100%) !important;transform:var(--tm-preview-slot-transform,none) !important;transform-origin:center !important;border-radius:var(--tm-preview-slot-radius,0) !important;clip-path:var(--tm-preview-slot-clip-path,none) !important;-webkit-mask-image:var(--tm-preview-slot-mask-image,none) !important;mask-image:var(--tm-preview-slot-mask-image,none) !important;-webkit-mask-size:var(--tm-preview-slot-mask-size,cover) !important;mask-size:var(--tm-preview-slot-mask-size,cover) !important;-webkit-mask-position:var(--tm-preview-slot-mask-position,center) !important;mask-position:var(--tm-preview-slot-mask-position,center) !important;-webkit-mask-repeat:var(--tm-preview-slot-mask-repeat,no-repeat) !important;mask-repeat:var(--tm-preview-slot-mask-repeat,no-repeat) !important;z-index:1;}',
            '.tm-follow.tm-follow-card-frame .tm-card-img>.tm-card-preview-slot{overflow:hidden !important;}',
            '.tm-follow.tm-follow-card-frame .tm-card-noimg{box-sizing:border-box;background:var(--tm-card-bg,rgba(127,127,127,.08)) !important;}',
            '.tm-follow.tm-follow-card-frame .tm-card-img::after{opacity:var(--tm-theme-card-frame-opacity,1) !important;}',
            '.tm-follow.tm-follow-card-frame .tm-card-menu,.tm-follow.tm-follow-card-frame .tm-card-check,.tm-follow.tm-follow-card-frame .tm-badge-on,.tm-follow.tm-follow-card-frame .tm-badge-star,.tm-follow.tm-follow-card-frame .tm-badge-freq{z-index:4 !important;}',
            '.tm-follow.tm-follow-grid .tm-card.no-img .tm-card-img::before{background-image:var(--tm-theme-surface-image,none) !important;background-size:var(--tm-theme-surface-size,cover) !important;background-position:var(--tm-theme-surface-position,center) !important;background-repeat:var(--tm-theme-surface-repeat,no-repeat) !important;opacity:var(--tm-theme-card-motif-opacity,0) !important;}',
            '.tm-follow.tm-follow-card-frame .tm-card.no-img .tm-card-img::before{opacity:0 !important;}',
            '.tm-follow .tm-head,.tm-follow .tm-bottombar{backdrop-filter:var(--tm-panel-blur,none) !important;box-shadow:var(--tm-panel-shadow,none) !important;}',
            '.tm-follow .tm-sheet{background:var(--tm-bg2,var(--SmartThemeBackgroundColor,#1a1a1e)) !important;border-radius:var(--tm-panel-radius,18px) var(--tm-panel-radius,18px) 0 0 !important;box-shadow:var(--tm-panel-shadow,none) !important;backdrop-filter:var(--tm-panel-blur,none) !important;}',
            '.tm-follow .tm-icon-btn,.tm-follow .tm-catbtn,.tm-follow .tm-sort-chip,.tm-follow .tm-grid-size-btn,.tm-follow .tm-batch-btn,.tm-follow .tm-bottom-btn,.tm-follow .tm-card-menu,.tm-follow .tm-search-inp,.tm-follow .tm-field input[type=text],.tm-follow .tm-field select,.tm-follow .tm-field textarea{border-radius:var(--tm-control-radius,8px) !important;box-shadow:var(--tm-control-shadow,none) !important;}',
            '.tm-follow .tm-catbtn,.tm-follow .tm-sort-chip,.tm-follow .tm-grid-size-btn,.tm-follow .tm-batch-btn,.tm-follow .tm-bottom-btn,.tm-follow .tm-search-inp,.tm-follow .tm-field input[type=text],.tm-follow .tm-field select,.tm-follow .tm-field textarea{border:var(--tm-control-border-style,1px solid transparent) !important;}',
            '.tm-follow .tm-catbtn.on,.tm-follow .tm-sort-chip.on,.tm-follow .tm-bottom-btn.on{background:var(--SmartThemeQuoteColor,#7c6daf) !important;border-color:var(--SmartThemeQuoteColor,#7c6daf) !important;color:var(--tm-accent-text,#fff) !important;}',
            '.tm-follow .tm-catbtn:hover,.tm-follow .tm-sort-chip:hover,.tm-follow .tm-grid-size-btn:hover,.tm-follow .tm-batch-btn:hover,.tm-follow .tm-bottom-btn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf) !important;}',
            '.tm-lightbox{position:absolute;inset:0;z-index:3;background:rgba(0,0,0,.92);pointer-events:auto;display:flex;align-items:center;justify-content:center;animation:tm-popin .18s ease;}',
            '.tm-lb-img{max-width:92vw;max-height:88vh;object-fit:contain;border-radius:10px;box-shadow:0 8px 40px rgba(0,0,0,.6);user-select:none;}',
            '.tm-lb-close{position:absolute;top:18px;right:20px;background:rgba(255,255,255,.12);border:none;color:#fff;font-size:1.3em;width:40px;height:40px;border-radius:50%;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:.15s;z-index:2147483647;}',
            '.tm-lb-close:hover{background:rgba(255,255,255,.25);}',
            '.tm-lb-nav{position:absolute;top:50%;transform:translateY(-50%);background:rgba(255,255,255,.12);border:none;color:#fff;font-size:1.2em;width:42px;height:42px;border-radius:50%;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:.15s;z-index:2147483647;}',
            '.tm-lb-nav:hover{background:rgba(255,255,255,.25);}',
            '.tm-lb-prev{left:14px;} .tm-lb-next{right:14px;}',
            '.tm-lb-counter{position:absolute;bottom:20px;left:50%;transform:translateX(-50%);color:rgba(255,255,255,.6);font-size:.82em;background:rgba(0,0,0,.4);padding:4px 14px;border-radius:20px;z-index:2147483647;}',
            '.tm-lb-name{position:absolute;top:20px;left:50%;transform:translateX(-50%);color:#fff;font-size:.9em;font-weight:600;background:rgba(0,0,0,.4);padding:5px 16px;border-radius:20px;max-width:60vw;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;z-index:2147483647;}',
        ].join('');
        document.head.appendChild(s);
    };
})(window);
