(function (global) {
    var ns = global.ThemeMgrModules = global.ThemeMgrModules || {};

    ns.injectStyles = function () {
        var old = document.getElementById('tm-style');
        if (old) old.parentNode.removeChild(old);
        var s = document.createElement('style');
        s.id = 'tm-style';
        s.textContent = [
            '@keyframes tm-fadein{from{opacity:0}to{opacity:1}}',
            '@keyframes tm-sheet-up{from{transform:translateY(100%)}to{transform:translateY(0)}}',
            '@keyframes tm-popin{from{opacity:0;transform:scale(.95)}to{opacity:1;transform:scale(1)}}',
            '@keyframes tm-spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}',
            '.tm-light{--tm-bg:#f5f5f7;--tm-bg2:#ececef;--tm-text:#111;--tm-border:rgba(0,0,0,.1);--tm-card-bg:rgba(0,0,0,.04);--tm-head-bg:rgba(255,255,255,.8);}',
            '.tm-dark{--tm-bg:#16161a;--tm-bg2:#1e1e24;--tm-text:#eee;--tm-border:rgba(255,255,255,.08);--tm-card-bg:rgba(255,255,255,.05);--tm-head-bg:rgba(0,0,0,.3);}',
            '.tm-overlay{position:fixed;top:0;left:0;right:0;bottom:0;width:100vw;height:100dvh;z-index:2147483647;',
            'background:var(--tm-bg,var(--SmartThemeBackgroundColor,#16161a));',
            'color:var(--tm-text,var(--SmartThemeBodyColor,#eee));',
            'display:flex;flex-direction:column;animation:tm-fadein .18s ease;font-size:14px;}',
            '.tm-box{width:100%;height:100%;min-height:0;display:flex;flex-direction:column;overflow:hidden;}',
            '.tm-head{display:flex;align-items:center;gap:8px;padding:12px 15px;padding-top:max(12px, env(safe-area-inset-top, 12px));flex-shrink:0;border-bottom:1px solid rgba(127,127,127,.1);background:rgba(0,0,0,.12);}',
            '.tm-head-title{font-weight:700;font-size:1.05em;display:flex;align-items:center;gap:7px;flex:1;min-width:0;}',
            '.tm-head-title i{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-version{align-self:flex-end;font-size:.58em;font-weight:700;line-height:1;padding:0 0 2px;color:var(--tm-text);opacity:.55;flex-shrink:0;}',
            '.tm-head-actions{display:flex;align-items:center;gap:4px;}',
            '.tm-icon-btn{cursor:pointer;background:none;border:none;opacity:.55;font-size:1.15em;',
            'width:34px;height:34px;border-radius:50%;display:flex;align-items:center;justify-content:center;transition:.18s;color:inherit;flex-shrink:0;}',
            '.tm-icon-btn:hover{opacity:1;background:rgba(127,127,127,.12);color:var(--SmartThemeQuoteColor,#7c6daf);}',
'.tm-search-bar{display:none;padding:8px 15px;border-bottom:1px solid rgba(127,127,127,.08);background:rgba(0,0,0,.06);flex-shrink:0;}',
            '.tm-search-bar.open{display:flex;align-items:center;gap:8px;}',
            '.tm-search-wrap{flex:1;position:relative;display:flex;align-items:center;}',
            '.tm-search-wrap i{position:absolute;left:10px;opacity:.4;font-size:.85em;pointer-events:none;}',
            '.tm-search-inp{width:100%;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;padding:7px 32px 7px 30px;font-size:.85em;font-family:inherit;box-sizing:border-box;}',
            '.tm-search-inp:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-search-clear{background:none;border:none;color:inherit;opacity:.4;cursor:pointer;font-size:.9em;padding:4px;line-height:1;}',
            '.tm-search-clear:hover{opacity:.9;}',
            '.tm-catbar{display:flex;gap:6px;padding:8px 15px;overflow-x:auto;flex-wrap:nowrap;flex-shrink:0;-webkit-overflow-scrolling:touch;scrollbar-width:none;border-bottom:1px solid rgba(127,127,127,.08);}',
            '.tm-catbar::-webkit-scrollbar{display:none;}',
            '.tm-catbtn{padding:5px 14px;border-radius:18px;font-size:.78em;cursor:pointer;white-space:nowrap;flex-shrink:0;border:1px solid rgba(127,127,127,.15);background:rgba(127,127,127,.06);transition:all .15s;color:inherit;font-family:inherit;}',
            '.tm-catbtn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-catbtn.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;border-color:var(--SmartThemeQuoteColor,#7c6daf);font-weight:600;}',
            '.tm-sortbar{display:none;padding:6px 15px;border-bottom:1px solid rgba(127,127,127,.08);flex-shrink:0;gap:6px;align-items:center;overflow-x:auto;scrollbar-width:none;}',
            '.tm-sortbar.open{display:flex;}',
            '.tm-sortbar::-webkit-scrollbar{display:none;}',
            '.tm-sort-chip{padding:4px 12px;border-radius:14px;font-size:.72em;cursor:pointer;white-space:nowrap;flex-shrink:0;border:1px solid rgba(127,127,127,.12);background:rgba(127,127,127,.04);transition:all .15s;color:inherit;font-family:inherit;}',
            '.tm-sort-chip:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-sort-chip.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-sort-divider{width:1px;height:18px;background:rgba(127,127,127,.18);flex-shrink:0;margin:0 2px;}',
            '.tm-grid-size-label{font-size:.72em;opacity:.4;flex-shrink:0;white-space:nowrap;}',
            '.tm-grid-size-btn{width:26px;height:26px;border-radius:50%;border:1px solid rgba(127,127,127,.16);background:rgba(127,127,127,.06);color:inherit;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:.72em;transition:.15s;flex-shrink:0;}',
            '.tm-grid-size-btn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.12);}',
            '.tm-grid-area{flex:1;overflow-y:auto;padding:12px 12px 8px;}',
            '.tm-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(var(--tm-grid-card-min,108px),1fr));gap:9px;}',
            '.tm-loading{display:flex;flex-direction:column;align-items:center;gap:12px;padding:60px 20px;opacity:.5;}',
            '.tm-loading i{font-size:2em;animation:tm-spin 1s linear infinite;}',
            '.tm-card{border-radius:10px;overflow:hidden;position:relative;cursor:pointer;transition:all .18s;border:2px solid transparent;display:flex;flex-direction:column;}',
            '.tm-card:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,.25);}',
            '.tm-card.on{border-color:var(--SmartThemeQuoteColor,#7c6daf);box-shadow:0 0 0 1px var(--SmartThemeQuoteColor,#7c6daf),0 4px 16px rgba(0,0,0,.2);}',
            '.tm-card-img{width:100%;aspect-ratio:4/3;position:relative;background:rgba(127,127,127,.1);display:flex;align-items:center;justify-content:center;overflow:hidden;flex-shrink:0;}',
            '.tm-card-img img{width:100%;height:100%;object-fit:cover;display:block;}',
            '@media (hover:hover){.tm-card-menu{opacity:0;} .tm-card:hover .tm-card-menu{opacity:.85;}}',
            '.tm-card-info{padding:5px 7px 6px;background:var(--tm-card-bg,rgba(127,127,127,.06));min-height:36px;box-sizing:border-box;}',
            '.tm-card-name{font-size:.8em;font-weight:600;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--tm-text,#eee);}',
            '.tm-card-tag{font-size:.68em;line-height:1.2;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--tm-text,#aaa);opacity:.5;}',
            '.tm-card-noimg{display:flex;flex-direction:column;align-items:center;gap:6px;opacity:.3;font-size:.75em;width:100%;height:100%;justify-content:center;}',
            '.tm-card-noimg i{font-size:2em;}',
            '.tm-card.no-img{background:rgba(127,127,127,.08);}',
            '.tm-badge-on{position:absolute;top:5px;right:5px;width:20px;height:20px;border-radius:50%;background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;display:flex;align-items:center;justify-content:center;font-size:.6em;box-shadow:0 2px 6px rgba(0,0,0,.3);}',
            '.tm-badge-star{position:absolute;top:5px;left:5px;font-size:.85em;color:#f0b860;filter:drop-shadow(0 1px 3px rgba(0,0,0,.5));}',
            '.tm-badge-freq{position:absolute;bottom:5px;left:5px;padding:1px 6px;border-radius:8px;font-size:.6em;font-weight:600;background:rgba(0,0,0,.55);color:#fff;backdrop-filter:blur(4px);}',
            '.tm-card-menu{position:absolute;bottom:4px;right:4px;width:24px;height:24px;border-radius:50%;background:rgba(0,0,0,.45);backdrop-filter:blur(4px);border:none;color:#fff;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:.7em;opacity:.65;transition:opacity .15s;z-index:1;}',
            '.tm-card-menu:hover{opacity:1 !important;background:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-card-check{position:absolute;top:5px;left:5px;width:22px;height:22px;border-radius:50%;border:2px solid rgba(255,255,255,.6);background:rgba(0,0,0,.3);backdrop-filter:blur(4px);display:flex;align-items:center;justify-content:center;font-size:.6em;color:transparent;cursor:pointer;transition:all .15s;z-index:1;}',
            '.tm-card-check.checked{background:var(--SmartThemeQuoteColor,#7c6daf);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;}',
            '.tm-card.batch-sel{border-color:var(--SmartThemeQuoteColor,#7c6daf);opacity:.85;}',
            '.tm-batch-area{flex-shrink:0;}',
            '.tm-batch-bar{display:flex;align-items:center;gap:6px;padding:8px 12px;background:rgba(124,109,175,.06);border-bottom:1px solid rgba(124,109,175,.15);flex-wrap:nowrap;overflow-x:auto;-webkit-overflow-scrolling:touch;scrollbar-width:none;}',
            '.tm-batch-bar::-webkit-scrollbar{display:none;}',
            '.tm-batch-info{font-size:.82em;font-weight:600;color:var(--SmartThemeQuoteColor,#7c6daf);white-space:nowrap;flex-shrink:0;}',
            '.tm-batch-divider{width:1px;height:16px;background:rgba(127,127,127,.25);flex-shrink:0;margin:0 2px;}',
            '.tm-batch-acts{display:flex;gap:5px;flex-shrink:0;flex-wrap:nowrap;}',
            '.tm-batch-btn{padding:5px 10px;border-radius:6px;font-size:.78em;cursor:pointer;border:1px solid rgba(127,127,127,.2);background:rgba(127,127,127,.07);color:inherit;font-family:inherit;transition:.15s;white-space:nowrap;flex-shrink:0;}',
            '.tm-batch-btn:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.1);}',
            '.tm-batch-btn.danger{border-color:#e57373;color:#e57373;}',
            '.tm-batch-btn.danger:hover{background:#e57373;color:#fff;}',
            '.tm-empty{display:flex;flex-direction:column;align-items:center;gap:10px;padding:40px 20px;opacity:.35;font-size:.9em;text-align:center;}',
            '.tm-empty i{font-size:2.6em;}',
            '.tm-bottombar{display:flex !important;align-items:center;gap:6px;padding:10px 14px;padding-bottom:max(10px, env(safe-area-inset-bottom, 10px));flex-shrink:0;border-top:1px solid rgba(127,127,127,.1);background:rgba(0,0,0,.12);}',
            '.tm-bottom-status{flex:1;min-width:0;display:flex;align-items:center;gap:7px;cursor:pointer;border-radius:8px;padding:5px 7px;transition:.15s;border:1px solid transparent;}',
            '.tm-bottom-status:hover{background:rgba(127,127,127,.08);border-color:rgba(127,127,127,.12);}',
            '.tm-status-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0;}',
            '.tm-status-dot.gray{background:rgba(127,127,127,.5);}',
            '.tm-status-dot.green{background:#4caf50;}',
            '.tm-status-text{font-size:.82em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;opacity:.9;}',
            '.tm-bottom-btn{width:36px;height:36px;border-radius:50%;border:1px solid rgba(127,127,127,.15);background:rgba(127,127,127,.06);color:inherit;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:.9em;transition:.18s;flex-shrink:0;}',
            '.tm-bottom-btn:hover{background:rgba(127,127,127,.15);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-bottom-btn.on{background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
'.tm-sheet-overlay{position:absolute !important;inset:0 !important;z-index:1 !important;background:rgba(0,0,0,.45) !important;pointer-events:auto !important;}',
            '.tm-sheet{position:absolute;bottom:0;left:0;right:0;max-height:88vh;max-height:88dvh;background:var(--tm-bg2,var(--SmartThemeBackgroundColor,#1a1a1e));color:var(--tm-text,var(--SmartThemeBodyColor,#eee));border-radius:18px 18px 0 0;overflow-y:auto;animation:tm-sheet-up .25s ease;border:1px solid rgba(127,127,127,.15);border-bottom:none;}',
            '.tm-sheet-handle{width:36px;height:4px;border-radius:2px;background:rgba(127,127,127,.25);margin:10px auto 4px;}',
            '.tm-sheet-content{padding:4px 20px 32px;}',
            '.tm-sheet-title{font-weight:700;font-size:1.05em;padding:10px 0 14px;display:flex;align-items:center;gap:8px;}',
            '.tm-sheet-title i{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-ctx-item{display:flex;align-items:center;gap:12px;padding:14px 4px;cursor:pointer;border-bottom:1px solid rgba(127,127,127,.08);transition:.15s;border-radius:0;}',
            '.tm-ctx-item:last-child{border-bottom:none;}',
            '.tm-ctx-item:hover{color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-ctx-item i{width:20px;text-align:center;opacity:.75;font-size:1em;}',
            '.tm-ctx-item.danger{color:#e57373;}',
            '.tm-ctx-item.danger:hover{color:#ef5350;}',
            '.tm-ctx-theme-name{font-size:.85em;opacity:.5;padding:2px 0 10px;border-bottom:1px solid rgba(127,127,127,.1);margin-bottom:4px;}',
            '.tm-sec-title{font-size:.75em;font-weight:700;opacity:.55;text-transform:uppercase;letter-spacing:.07em;padding:10px 0 7px;}',
            '.tm-divider{height:1px;background:rgba(127,127,127,.12);margin:6px 0 12px;}',
            '.tm-hint{font-size:.76em;opacity:.5;line-height:1.4;}',
            '.tm-btn-row{display:flex;gap:8px;flex-wrap:wrap;}',
            '.tm-data-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:8px;}',
            '.tm-data-grid .tm-btn{display:flex;align-items:center;justify-content:center;gap:5px;min-width:0;padding:8px 5px;font-size:.78em;line-height:1.2;white-space:nowrap;}',
            '.tm-btn{padding:8px 16px;border-radius:8px;border:none;cursor:pointer;font-size:.87em;font-weight:600;transition:.18s;font-family:inherit;}',
            '.tm-btn-safe{background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;}',
            '.tm-btn-safe:hover{filter:brightness(1.1);}',
            '.tm-btn-outline{background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.22);color:inherit;}',
            '.tm-btn-outline:hover{background:rgba(127,127,127,.15);border-color:var(--SmartThemeQuoteColor,#7c6daf);color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-btn-danger{background:rgba(229,115,115,.1);border:1px solid #e57373;color:#e57373;}',
            '.tm-btn-danger:hover{background:#e57373;color:#fff;}',
            '.tm-field{display:flex;flex-direction:column;gap:5px;margin-bottom:10px;}',
            '.tm-field label{font-size:.8em;opacity:.7;font-weight:500;}',
            '.tm-field input[type=text],.tm-field select,.tm-field textarea{background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;padding:9px 11px;font-size:.9em;width:100%;box-sizing:border-box;font-family:inherit;}',
            '.tm-field textarea{resize:none;}',
            '.tm-field input:focus,.tm-field select:focus,.tm-field textarea:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-fab-custom-row{display:flex;align-items:center;gap:10px;}',
            '.tm-fab-preview{width:48px;height:48px;overflow:hidden;display:flex;align-items:center;justify-content:center;flex-shrink:0;}',
            '.tm-fab-preview img{width:100%;height:100%;object-fit:contain;}',
            '.tm-fab-default-preview{width:100%;height:100%;border-radius:50%;background:var(--SmartThemeQuoteColor,#7c6daf);display:flex;align-items:center;justify-content:center;color:#fff;}',
            '.tm-fab-custom-actions{display:flex;gap:6px;flex:1;flex-wrap:wrap;}',
            '.tm-fab-custom-actions .tm-btn{font-size:.8em;flex:1 1 120px;}',
            '.tm-range{width:100%;accent-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-import-cat-list{display:flex;flex-direction:column;gap:7px;margin:8px 0 12px;max-height:42vh;overflow:auto;}',
            '.tm-import-cat-item{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:8px;background:rgba(127,127,127,.06);border:1px solid rgba(127,127,127,.1);}',
            '.tm-import-cat-item span{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:.88em;}',
            '.tm-import-cat-item small{opacity:.45;font-size:.75em;white-space:nowrap;}',
            '.tm-import-cat-tools{display:flex;gap:8px;justify-content:flex-end;margin-bottom:8px;}',
            '.tm-cat-export-item{display:flex;align-items:center;gap:9px;width:100%;padding:9px 10px;border-radius:8px;background:rgba(127,127,127,.06);border:1px solid rgba(127,127,127,.1);color:inherit;font-family:inherit;text-align:left;cursor:pointer;}',
            '.tm-cat-export-item:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.1);}',
            '.tm-cat-export-item span{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:.88em;}',
            '.tm-cat-export-item small{opacity:.45;font-size:.75em;white-space:nowrap;}',
            '.tm-frow{display:flex;gap:7px;align-items:stretch;}',
            '.tm-frow select{flex:1;}',
            '.tm-bg-bind-card{width:100%;display:grid;grid-template-columns:72px minmax(0,1fr) 18px;gap:10px;align-items:center;padding:8px;border-radius:8px;border:1px solid rgba(127,127,127,.2);background:rgba(127,127,127,.08);color:inherit;text-align:left;font-family:inherit;cursor:pointer;}',
            '.tm-bg-bind-card:hover{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.12);}',
            '.tm-bg-bind-thumb{height:48px;border-radius:7px;background-size:cover;background-position:center;background-color:rgba(127,127,127,.14);border:1px solid rgba(127,127,127,.14);display:flex;align-items:center;justify-content:center;overflow:hidden;}',
            '.tm-bg-bind-thumb.empty{background:repeating-linear-gradient(45deg,rgba(127,127,127,.08),rgba(127,127,127,.08) 8px,rgba(127,127,127,.16) 8px,rgba(127,127,127,.16) 16px);}',
            '.tm-bg-bind-thumb i{opacity:.4;font-size:1.2em;}',
            '.tm-bg-bind-info{min-width:0;}',
            '.tm-bg-bind-name{font-size:.88em;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-bg-bind-sub{font-size:.72em;opacity:.48;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-bg-bind-card>i{opacity:.35;}',
            '.tm-bg-picker-tools{display:grid;grid-template-columns:minmax(0,1fr) 34px 34px;gap:7px;align-items:center;margin-bottom:10px;}',
            '.tm-bg-search-wrap{display:flex;align-items:center;gap:7px;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.18);border-radius:8px;padding:0 9px;min-width:0;}',
            '.tm-bg-search-wrap i{opacity:.45;font-size:.85em;}',
            '.tm-bg-search-wrap input{flex:1;min-width:0;background:transparent;border:none;color:inherit;padding:8px 0;font-family:inherit;font-size:.86em;outline:none;}',
            '.tm-bg-picker-list{display:grid;grid-template-columns:repeat(auto-fill,minmax(var(--tm-bg-card-min,132px),1fr));gap:10px;padding-bottom:8px;}',
            '.tm-bg-picker-card{position:relative;display:flex;flex-direction:column;gap:6px;padding:7px;border-radius:8px;border:2px solid transparent;background:rgba(127,127,127,.06);color:inherit;font-family:inherit;text-align:left;cursor:pointer;min-width:0;}',
            '.tm-bg-picker-card:hover{background:rgba(127,127,127,.11);}',
            '.tm-bg-picker-card.on{border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-bg-picker-thumb{width:100%;aspect-ratio:4/3;border-radius:6px;background-size:cover;background-position:center;background-color:rgba(127,127,127,.12);border:1px solid rgba(127,127,127,.12);display:flex;align-items:center;justify-content:center;overflow:hidden;}',
            '.tm-bg-picker-thumb.empty{background:repeating-linear-gradient(45deg,rgba(127,127,127,.08),rgba(127,127,127,.08) 8px,rgba(127,127,127,.16) 8px,rgba(127,127,127,.16) 16px);}',
            '.tm-bg-picker-thumb i{opacity:.38;font-size:1.6em;}',
            '.tm-bg-picker-name{font-size:.75em;font-weight:600;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
            '.tm-bg-picker-card>i{position:absolute;top:9px;right:9px;color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(0,0,0,.35);border-radius:50%;opacity:0;}',
            '.tm-bg-picker-card.on>i{opacity:1;}',
            '.tm-bg-rename{position:absolute;right:8px;bottom:28px;width:26px;height:26px;border:none;border-radius:50%;background:rgba(0,0,0,.48);color:#fff;display:flex;align-items:center;justify-content:center;cursor:pointer;opacity:.72;z-index:1;}',
            '.tm-bg-rename:hover{opacity:1;background:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-imgarea{width:100%;height:160px;background:rgba(127,127,127,.06);border:2px dashed rgba(127,127,127,.25);border-radius:10px;display:flex;align-items:center;justify-content:center;cursor:pointer;overflow:hidden;transition:border-color .18s;}',
            '.tm-imgarea:hover,.tm-imgarea.drag{border-color:var(--SmartThemeQuoteColor,#7c6daf);background:rgba(127,127,127,.1);}',
            '.tm-imgph{display:flex;flex-direction:column;align-items:center;gap:6px;opacity:.4;font-size:.82em;pointer-events:none;}',
            '.tm-imgph i{font-size:1.8em;}',
            '.tm-imgarea img{width:100%;height:100%;object-fit:contain;}',
            '.tm-img-actions{display:flex;gap:7px;margin-top:7px;}',
            '.tm-crop-stage{width:100%;aspect-ratio:4/3;background:#111;border-radius:10px;overflow:hidden;border:1px solid rgba(127,127,127,.18);}',
            '.tm-crop-stage canvas{width:100%;height:100%;display:block;}',
            '.tm-crop-controls{display:grid;gap:8px;margin:10px 0 12px;}',
            '.tm-crop-controls label{display:grid;grid-template-columns:42px minmax(0,1fr);gap:8px;align-items:center;font-size:.78em;opacity:.78;}',
            '.tm-crop-controls input{width:100%;accent-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-edit-foot{display:flex;gap:9px;justify-content:flex-end;padding-top:14px;border-top:1px solid rgba(127,127,127,.1);margin-top:10px;}',
            '.tm-tags-wrap{display:flex;flex-wrap:wrap;gap:5px;margin-top:4px;}',
            '.tm-tag-chip{display:inline-flex;align-items:center;gap:4px;padding:3px 8px 3px 10px;border-radius:12px;background:var(--SmartThemeQuoteColor,#7c6daf);color:#fff;font-size:.78em;font-weight:500;}',
            '.tm-tag-chip-x{background:none;border:none;color:#fff;cursor:pointer;font-size:.85em;line-height:1;padding:0 2px;opacity:.7;}',
            '.tm-tag-chip-x:hover{opacity:1;}',
            '.tm-tag-add-row{display:flex;gap:6px;margin-top:6px;}',
            '.tm-tag-add-row input{flex:1;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;padding:6px 10px;font-size:.82em;font-family:inherit;box-sizing:border-box;}',
            '.tm-tag-add-row input:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-cat-item{display:flex;align-items:center;gap:8px;padding:9px 12px;background:rgba(127,127,127,.06);border-radius:9px;border:1px solid rgba(127,127,127,.1);transition:none;margin-bottom:7px;}',
            '.tm-cat-item:hover{background:rgba(127,127,127,.11);}',
            '.tm-cat-item.drag-over-top{border-top:2px solid var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-cat-item.drag-over-bottom{border-bottom:2px solid var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-cat-item.dragging{opacity:.3;}',
            '.tm-drag-handle{opacity:.35;cursor:grab;padding:0 6px;font-size:.9em;touch-action:none;}',
            '.tm-cat-name{flex:1;font-size:.88em;}',
            '.tm-cat-count{font-size:.74em;opacity:.45;}',
            '.tm-cat-add-row{display:flex;gap:8px;}',
            '.tm-cat-add-row input{flex:1;background:rgba(127,127,127,.08);border:1px solid rgba(127,127,127,.2);border-radius:8px;color:inherit;padding:8px 11px;font-size:.88em;font-family:inherit;box-sizing:border-box;}',
            '.tm-cat-add-row input:focus{outline:none;border-color:var(--SmartThemeQuoteColor,#7c6daf);}',
            '.tm-btn-sm{padding:5px 7px;border-radius:6px;cursor:pointer;font-size:.78em;background:rgba(127,127,127,.07);border:1px solid rgba(127,127,127,.14);transition:all .15s;color:inherit;font-family:inherit;}',
            '.tm-btn-sm:hover{background:rgba(127,127,127,.15);}',
            '.tm-row-inline{display:flex;align-items:center;justify-content:space-between;margin-bottom:6px;}',
            '.tm-row-inline label{opacity:.8;font-size:.88em;}',
            '.tm-chk{width:17px;height:17px;accent-color:var(--SmartThemeQuoteColor,#7c6daf);cursor:pointer;}',
            '.tm-storage-info{font-size:.72em;opacity:.45;padding:4px 0;}',
            '.tm-lightbox{position:absolute;inset:0;z-index:3;background:rgba(0,0,0,.92);pointer-events:auto;display:flex;align-items:center;justify-content:center;animation:tm-popin .18s ease;}',
            '.tm-lb-img{max-width:92vw;max-height:88vh;object-fit:contain;border-radius:10px;box-shadow:0 8px 40px rgba(0,0,0,.6);user-select:none;}',
            '.tm-lb-close{position:absolute;top:18px;right:20px;background:rgba(255,255,255,.12);border:none;color:#fff;font-size:1.3em;width:40px;height:40px;border-radius:50%;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:.15s;z-index:2147483647;}',
            '.tm-lb-close:hover{background:rgba(255,255,255,.25);}',
            '.tm-lb-nav{position:absolute;top:50%;transform:translateY(-50%);background:rgba(255,255,255,.12);border:none;color:#fff;font-size:1.2em;width:42px;height:42px;border-radius:50%;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:.15s;z-index:2147483647;}',
            '.tm-lb-nav:hover{background:rgba(255,255,255,.25);}',
            '.tm-lb-prev{left:14px;} .tm-lb-next{right:14px;}',
            '.tm-lb-counter{position:absolute;bottom:20px;left:50%;transform:translateX(-50%);color:rgba(255,255,255,.6);font-size:.82em;background:rgba(0,0,0,.4);padding:4px 14px;border-radius:20px;z-index:2147483647;}',
            '.tm-lb-name{position:absolute;top:20px;left:50%;transform:translateX(-50%);color:#fff;font-size:.9em;font-weight:600;background:rgba(0,0,0,.4);padding:5px 16px;border-radius:20px;max-width:60vw;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;z-index:2147483647;}',
        ].join('');
        document.head.appendChild(s);
    };
})(window);
